#!/usr/bin/env python3
# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
r"""Generate RTL and documentation collateral from OTP memory
map definition file (hjson).
"""
import argparse
import logging as log
import sys
from pathlib import Path
from typing import Dict

from mako import exceptions
from mako.template import Template

from lib.otp_mem_map import OtpMemMap
from lib.reggen.ip_block import IpBlock
from lib.reggen import gen_rtl

HEADER_COMMENT = '''
DO NOT EDIT THIS FILE DIRECTLY.
It has been generated with ./tools/scripts/gen_fuse_ctrl_partitions/gen_fuse_ctrl_partitions.py'''

HEADER_COMMENT_SV = HEADER_COMMENT.replace("\n", "\n// ")
HEADER_COMMENT_HJSON = HEADER_COMMENT_SV
HEADER_COMMENT_HTML = "<!--"+HEADER_COMMENT+"\n-->"

# # memory map source
# MMAP_DEFINITION_FILE = "src/fuse_ctrl/data/otp_ctrl_mmap.hjson"
# # documentation tables to generate
# PARTITIONS_TABLE_FILE = Path("otp_ctrl_partitions.md")
# DIGESTS_TABLE_FILE = Path("otp_ctrl_digests.md")
# MMAP_TABLE_FILE = Path("otp_ctrl_mmap.md")
# DESC_TABLE_FILE = Path("otp_ctrl_field_descriptions.md")

## Output paths
DATA_OUTPUT_PATH = Path("src") / "fuse_ctrl" / "data"
DOC_OUTPUT_PATH  = Path("src") / "fuse_ctrl" / "doc"
RTL_OUTPUT_PATH  = Path("src") / "fuse_ctrl" / "rtl"

## Doc table files
PARTITIONS_TABLE_FILE = "otp_ctrl_partitions.md"
DIGESTS_TABLE_FILE    = "otp_ctrl_digests.md"
MMAP_TABLE_FILE       = "otp_ctrl_mmap.md"
DESC_TABLE_FILE       = "otp_ctrl_field_descriptions.md"

## Templates
TEMPLATES_PATH = Path("src") / "fuse_ctrl" / "templates"

# Config templates
MMAP_TEMPLATE  = "otp_ctrl_mmap.hjson.tpl"
HJSON_TEMPLATE = "otp_ctrl.hjson.tpl"

# RTL templates
PART_PKG_TEMPLATE = "otp_ctrl_part_pkg.sv.tpl"
REG_PKG_TEMPLATE  = "reg_pkg.sv.tpl"
REG_TOP_TEMPLATE  = "reg_top.sv.tpl"

def render_template(template: str, target_path: Path, params: Dict[str, object]):
    try:
        tpl = Template(filename=str(template))
    except OSError as e:
        log.error(f"Error creating template: {e}")
        exit(1)

    try:
        expansion = tpl.render(**params)
    except exceptions.MakoException:
        log.error(exceptions.text_error_template().render())
        exit(1)

    try:
        with target_path.open(mode='w', encoding='UTF-8') as outfile:
            outfile.write(expansion)
    except OSError as e:
        log.error(f"Error rendering template: {e}")
        exit(1)

def main():
    parser = argparse.ArgumentParser(prog="gen_fuse_ctrl_partitions")

    parser.add_argument('--num_vendor_fuses',
                        type=int,
                        default=16,
                        help='Number of vendor-specific fuses')
    args = parser.parse_args()

    mmap_path = Path("src") / "fuse_ctrl" / "data"
    mmap_out = Path("src")
    params = {"num_vendor_fuses": 16}

    # Render mmap HJSON
    render_template(
        template=TEMPLATES_PATH / MMAP_TEMPLATE,
        target_path=DATA_OUTPUT_PATH / MMAP_TEMPLATE.replace(".tpl", ""),
        params={"num_vendor_fuses": args.num_vendor_fuses}
    )

    # Parse rendered mmap file
    otp_mmap = OtpMemMap.from_mmap_path(DATA_OUTPUT_PATH / MMAP_TEMPLATE.replace(".tpl", ""), None)

    # Render doc tables
    with open(DOC_OUTPUT_PATH/ PARTITIONS_TABLE_FILE, 'wb', buffering=2097152) as outfile:
        outfile.write(HEADER_COMMENT_HTML.encode('utf-8'))
        outfile.write(otp_mmap.create_partitions_table().encode('utf-8'))
        outfile.write('\n'.encode('utf-8'))

    with open(DOC_OUTPUT_PATH / DIGESTS_TABLE_FILE, 'wb', buffering=2097152) as outfile:
        outfile.write(HEADER_COMMENT_HTML.encode('utf-8'))
        outfile.write(otp_mmap.create_digests_table().encode('utf-8'))
        outfile.write('\n'.encode('utf-8'))

    with open(DOC_OUTPUT_PATH / MMAP_TABLE_FILE, 'wb', buffering=2097152) as outfile:
        outfile.write(HEADER_COMMENT_HTML.encode('utf-8'))
        outfile.write(otp_mmap.create_mmap_table().encode('utf-8'))
        outfile.write('\n'.encode('utf-8'))

    with open(DOC_OUTPUT_PATH / DESC_TABLE_FILE, 'wb', buffering=2097152) as outfile:
        outfile.write(HEADER_COMMENT_HTML.encode('utf-8'))
        outfile.write(otp_mmap.create_description_table().encode('utf-8'))
        outfile.write('\n'.encode('utf-8'))

    # Render block HJSON
    render_template(
        template=TEMPLATES_PATH / HJSON_TEMPLATE,
        target_path=DATA_OUTPUT_PATH / HJSON_TEMPLATE.replace(".tpl", ""),
        params={"otp_mmap": otp_mmap, "gen_comment": HEADER_COMMENT_HJSON}
    )

    output_path = Path("src") / "fuse_ctrl" / "rtl" 

    # Render partition package
    render_template(
        template=TEMPLATES_PATH / PART_PKG_TEMPLATE,
        target_path=RTL_OUTPUT_PATH / PART_PKG_TEMPLATE.replace(".tpl", ""),
        params={"otp_mmap": otp_mmap, "gen_comment": HEADER_COMMENT_SV}
    )

    # Render register files
    ip_block = IpBlock.from_path(str(DATA_OUTPUT_PATH / HJSON_TEMPLATE.replace(".tpl", "")), [])
    gen_rtl.gen_rtl(ip_block, str(RTL_OUTPUT_PATH))

if __name__ == "__main__":
    main()
