#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate independent interface RAL models and their base-address configuration."""

from __future__ import annotations

import argparse
import io
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, Mapping, Sequence

import yaml
from peakrdl_uvm import UVMExporter
from systemrdl import RDLCompileError, RDLCompiler
from systemrdl.component import Addrmap, Mem
from systemrdl.node import AddrmapNode


LICENSE_HEADER = """// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file was autogenerated by gen_ral.py.
// Do not edit manually.

"""

MAX_ADDRESS = (1 << 64) - 1
SV_KEYWORDS = frozenset("""
accept_on alias always always_comb always_ff always_latch and assert assign
assume automatic before begin bind bins binsof bit break buf bufif0 bufif1 byte
case casex casez cell chandle checker class clocking cmos config const constraint
context continue cover covergroup coverpoint cross deassign default defparam
design disable dist do edge else end endcase endchecker endclass endclocking
endconfig endfunction endgenerate endgroup endinterface endmodule endpackage
endprimitive endprogram endproperty endspecify endsequence endtable endtask enum
event eventually expect export extends extern final first_match for force foreach
forever fork forkjoin function generate genvar global highz0 highz1 if iff ifnone
ignore_bins illegal_bins implements implies import incdir include initial inout
input inside instance int integer interconnect interface intersect join join_any
join_none large let liblist library local localparam logic longint macromodule
matches medium modport module nand negedge nettype new nexttime nmos nor
noshowcancelled not notif0 notif1 null or output package packed parameter pmos
posedge primitive priority program property protected pull0 pull1 pulldown pullup
pulsestyle_ondetect pulsestyle_onevent pure rand randc randcase randsequence rcmos
real realtime ref reg reject_on release repeat restrict return rnmos rpmos rtran
rtranif0 rtranif1 s_always s_eventually s_nexttime s_until s_until_with scalared
sequence shortint shortreal showcancelled signed small soft solve specify specparam
static string strong strong0 strong1 struct super supply0 supply1 sync_accept_on
sync_reject_on table tagged task this throughout time timeprecision timeunit tran
tranif0 tranif1 tri tri0 tri1 triand trior trireg type typedef union unique unique0
unsigned until until_with untyped use uwire var vectored virtual void wait wait_order
wand weak weak0 weak1 while wildcard wire with within wor xnor xor
""".split())


class RecipeError(RuntimeError):
    """Raised for an invalid recipe or failed generation."""


class CheckError(RecipeError):
    """Raised when check-only mode finds missing or stale output."""


class _RecipeLoader(yaml.SafeLoader):
    def construct_mapping(self, node: yaml.MappingNode, deep: bool = False) -> dict:
        result = {}
        for key_node, value_node in node.value:
            key = self.construct_object(key_node, deep=deep)
            if not isinstance(key, str):
                raise RecipeError(f"YAML mapping keys must be strings at {key_node.start_mark}")
            if key in result:
                raise RecipeError(f"duplicate YAML key '{key}' at {key_node.start_mark}")
            result[key] = self.construct_object(value_node, deep=deep)
        return result


@dataclass(frozen=True)
class OutputConfig:
    path: Path
    class_name: str
    export_as_package: bool
    reuse_class_definitions: bool
    use_uvm_factory: bool
    memory_instance: str | None


@dataclass(frozen=True)
class RdlConfig:
    file: Path
    definition: str
    parameters: tuple[tuple[str, str | int | bool], ...]
    include_paths: tuple[Path, ...]
    defines: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class InterfaceConfig:
    name: str
    rdl: RdlConfig
    base_address: int
    output: OutputConfig


@dataclass(frozen=True)
class Recipe:
    config_output: Path
    interfaces: tuple[InterfaceConfig, ...]


@dataclass(frozen=True)
class RenderedOutput:
    job_name: str
    path: Path
    content: str


class _ExportBuffer(io.StringIO):
    def __init__(self, output_path: Path):
        super().__init__()
        self._output_path = output_path

    def __fspath__(self) -> str:
        return os.fspath(self._output_path)


def _expect_mapping(value: Any, location: str) -> Mapping[str, Any]:
    if not isinstance(value, dict):
        raise RecipeError(f"{location} must be a mapping")
    return value


def _expect_list(value: Any, location: str) -> Sequence[Any]:
    if not isinstance(value, list):
        raise RecipeError(f"{location} must be a list")
    return value


def _check_keys(
    value: Mapping[str, Any],
    location: str,
    required: set[str],
    optional: set[str] = frozenset(),
) -> None:
    missing = sorted(required - value.keys())
    unknown = sorted(value.keys() - required - optional)
    if missing:
        raise RecipeError(f"{location} is missing required key(s): {', '.join(missing)}")
    if unknown:
        raise RecipeError(f"{location} has unknown key(s): {', '.join(unknown)}")


def _expect_nonempty_string(value: Any, location: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise RecipeError(f"{location} must be a non-empty string")
    return value


def _expect_bool(value: Any, location: str) -> bool:
    if not isinstance(value, bool):
        raise RecipeError(f"{location} must be a boolean")
    return value


def _expect_identifier(
    value: Any, location: str, *, systemverilog: bool = False
) -> str:
    text = _expect_nonempty_string(value, location)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", text):
        raise RecipeError(f"{location} must be an identifier")
    if systemverilog and text in SV_KEYWORDS:
        raise RecipeError(f"{location} must not be a SystemVerilog keyword: {text}")
    return text


def _resolve_path(recipe_dir: Path, value: Any, location: str) -> Path:
    text = _expect_nonempty_string(value, location)
    path = Path(text)
    if not path.is_absolute():
        path = recipe_dir / path
    return path.resolve()


def _parse_values(
    value: Any, location: str
) -> tuple[tuple[str, str | int | bool], ...]:
    entries = _expect_mapping(value, location)
    result = []
    for name, raw_value in entries.items():
        _expect_identifier(name, f"{location} key")
        if not isinstance(raw_value, (str, int, bool)):
            raise RecipeError(f"{location}.{name} must be a string, integer, or boolean")
        result.append((name, raw_value))
    return tuple(result)


def _parse_parameters(
    value: Any, location: str
) -> tuple[tuple[str, str | int | bool], ...]:
    parameters = _parse_values(value, location)
    for name, parameter in parameters:
        if type(parameter) is int and not 0 <= parameter <= MAX_ADDRESS:
            raise RecipeError(f"{location}.{name} must be an unsigned 64-bit integer")
    return parameters


def _parse_interface(raw_job: Any, recipe_dir: Path, index: int) -> InterfaceConfig:
    location = f"interfaces[{index}]"
    job = _expect_mapping(raw_job, location)
    _check_keys(
        job,
        location,
        {"name", "rdl", "base_address", "output"},
    )

    name = _expect_identifier(job["name"], f"{location}.name")
    base_address = job["base_address"]
    if type(base_address) is not int or not 0 <= base_address <= MAX_ADDRESS:
        raise RecipeError(f"{location}.base_address must be an unsigned 64-bit integer")
    rdl_location = f"{location}.rdl"
    raw_rdl = _expect_mapping(job["rdl"], rdl_location)
    _check_keys(
        raw_rdl, rdl_location, {"file", "definition", "parameters"},
        {"include_paths", "defines"},
    )
    raw_include_paths = _expect_list(
        raw_rdl.get("include_paths", []), f"{rdl_location}.include_paths"
    )
    include_paths = tuple(
        _resolve_path(
            recipe_dir,
            value,
            f"{rdl_location}.include_paths[{include_index}]",
        )
        for include_index, value in enumerate(raw_include_paths)
    )

    defines = tuple(
        (key, str(int(value)) if isinstance(value, bool) else str(value))
        for key, value in _parse_values(
            raw_rdl.get("defines", {}), f"{rdl_location}.defines"
        )
    )
    rdl = RdlConfig(
        file=_resolve_path(recipe_dir, raw_rdl["file"], f"{rdl_location}.file"),
        definition=_expect_identifier(
            raw_rdl["definition"], f"{rdl_location}.definition"
        ),
        parameters=_parse_parameters(raw_rdl["parameters"], f"{rdl_location}.parameters"),
        include_paths=include_paths,
        defines=defines,
    )

    raw_output = _expect_mapping(job["output"], f"{location}.output")
    _check_keys(
        raw_output,
        f"{location}.output",
        {"path", "class_name"},
        {
            "format",
            "reuse_class_definitions",
            "use_uvm_factory",
            "memory_instance",
        },
    )
    output_path = _resolve_path(
        recipe_dir, raw_output["path"], f"{location}.output.path"
    )
    output_format = raw_output.get("format", "package")
    if output_format not in ("package", "include"):
        raise RecipeError(
            f"{location}.output.format must be 'package' or 'include'"
        )
    expected_suffix = ".sv" if output_format == "package" else ".svh"
    if output_path.suffix != expected_suffix:
        raise RecipeError(
            f"{location}.output.path must end in '{expected_suffix}' "
            f"for format '{output_format}'"
        )
    _expect_identifier(output_path.stem, f"{location}.output.path stem", systemverilog=True)
    reuse_class_definitions = _expect_bool(
        raw_output.get("reuse_class_definitions", False),
        f"{location}.output.reuse_class_definitions",
    )
    use_uvm_factory = _expect_bool(
        raw_output.get("use_uvm_factory", False),
        f"{location}.output.use_uvm_factory",
    )
    memory_instance = None
    if "memory_instance" in raw_output:
        memory_instance = _expect_identifier(
            raw_output["memory_instance"], f"{location}.output.memory_instance",
            systemverilog=True,
        )
    output = OutputConfig(
        path=output_path,
        class_name=_expect_identifier(
            raw_output["class_name"], f"{location}.output.class_name", systemverilog=True
        ),
        export_as_package=output_format == "package",
        reuse_class_definitions=reuse_class_definitions,
        use_uvm_factory=use_uvm_factory,
        memory_instance=memory_instance,
    )

    return InterfaceConfig(name=name, rdl=rdl, base_address=base_address, output=output)


def load_recipe(recipe_path: Path) -> Recipe:
    recipe_path = recipe_path.resolve()
    try:
        with recipe_path.open("r", encoding="utf-8") as recipe_file:
            raw_recipe = yaml.load(recipe_file, Loader=_RecipeLoader)
    except FileNotFoundError as error:
        raise RecipeError(f"recipe does not exist: {recipe_path}") from error
    except OSError as error:
        raise RecipeError(f"cannot read recipe {recipe_path}: {error}") from error
    except yaml.YAMLError as error:
        raise RecipeError(f"invalid YAML in recipe {recipe_path}: {error}") from error

    recipe = _expect_mapping(raw_recipe, "recipe")
    if type(recipe.get("schema_version")) is not int or recipe["schema_version"] != 2:
        raise RecipeError(
            "recipe.schema_version must be 2; migrate legacy exports to interfaces "
            "with local rdl, parameters, base_address, output, and config_output"
        )
    _check_keys(recipe, "recipe", {"schema_version", "interfaces", "config_output"})
    config_output = _resolve_path(
        recipe_path.parent, recipe["config_output"], "recipe.config_output"
    )
    if config_output.suffix != ".sv":
        raise RecipeError("recipe.config_output must end in '.sv'")
    _expect_identifier(config_output.stem, "recipe.config_output stem", systemverilog=True)

    raw_interfaces = _expect_list(recipe["interfaces"], "recipe.interfaces")
    if not raw_interfaces:
        raise RecipeError("recipe.interfaces must not be empty")
    jobs = tuple(
        _parse_interface(raw_job, recipe_path.parent, index)
        for index, raw_job in enumerate(raw_interfaces)
    )
    names: set[str] = set()
    packages = {config_output.stem}
    include_guards: set[str] = set()
    classes: set[str] = set()
    for job in jobs:
        symbol = job.name.upper()
        if symbol in names:
            raise RecipeError(f"duplicate interface name or base-address symbol: {job.name}")
        names.add(symbol)
        if job.output.export_as_package:
            if job.output.path.stem in packages:
                raise RecipeError(f"duplicate package name: {job.output.path.stem}")
            packages.add(job.output.path.stem)
        else:
            guard = job.output.path.name.replace(".", "_").upper()
            if guard in include_guards:
                raise RecipeError(f"duplicate include guard: {guard}")
            include_guards.add(guard)
        if job.output.class_name in classes:
            raise RecipeError(f"duplicate output class_name: {job.output.class_name}")
        classes.add(job.output.class_name)

    outputs: set[Path] = set()
    inputs = {recipe_path, *(job.rdl.file for job in jobs)}
    for output in (config_output, *(job.output.path for job in jobs)):
        if output in outputs:
            raise RecipeError(f"multiple outputs target {output}")
        if output in inputs:
            raise RecipeError(
                f"output conflicts with a recipe or source input: {output}"
            )
        outputs.add(output)
    return Recipe(config_output=config_output, interfaces=jobs)


def _validate_input_paths(job: InterfaceConfig) -> None:
    if not job.rdl.file.is_file():
        raise RecipeError(f"interface '{job.name}' RDL file does not exist: {job.rdl.file}")
    for include_path in job.rdl.include_paths:
        if not include_path.is_dir():
            raise RecipeError(
                f"interface '{job.name}' include path is not a directory: "
                f"{include_path}"
            )


def _elaborate_memory(compiler: RDLCompiler, job: InterfaceConfig) -> AddrmapNode:
    # Pass values through elaborate(), not interpolated RDL text. The wrapper
    # only forwards scalar parameters to an external instance of the local type.
    wrapper_name = job.output.class_name
    if wrapper_name in compiler.root.comp_defs:
        raise RecipeError(f"memory wrapper class_name conflicts with RDL definition: {wrapper_name}")
    declarations = []
    assignments = []
    for name, value in job.rdl.parameters:
        parameter_type = (
            "boolean" if isinstance(value, bool)
            else "longint unsigned" if isinstance(value, int)
            else "string"
        )
        declarations.append(f"{parameter_type} \\{name}")
        assignments.append(f".\\{name}(\\{name})")
    parameters = "#(" + ", ".join(declarations) + ")" if declarations else ""
    arguments = "#(" + ", ".join(assignments) + ")" if assignments else ""
    instance = job.output.memory_instance or "memory"
    wrapper = (
        f"addrmap \\{wrapper_name} {parameters} {{\n"
        f"    external \\{job.rdl.definition} {arguments} \\{instance} @ 0;\n"
        "};\n"
    )
    with TemporaryDirectory(prefix="gen_ral_") as directory:
        path = Path(directory) / "memory_wrapper.rdl"
        path.write_text(wrapper, encoding="ascii")
        compiler.compile_file(os.fspath(path))
        return compiler.elaborate(
            top_def_name=wrapper_name,
            inst_name=job.output.class_name,
            parameters=dict(job.rdl.parameters),
        ).top


def render_interface(
    job: InterfaceConfig, *, input_paths: set[Path] | None = None
) -> RenderedOutput:
    _validate_input_paths(job)
    compiler = RDLCompiler()
    try:
        info = compiler.compile_file(
            os.fspath(job.rdl.file),
            incl_search_paths=[os.fspath(path) for path in job.rdl.include_paths],
            defines=dict(job.rdl.defines),
        )
        if input_paths is not None:
            input_paths.update(Path(path).resolve() for path in info.included_files)
        definition = compiler.root.comp_defs.get(job.rdl.definition)
        if isinstance(definition, Mem):
            selected = _elaborate_memory(compiler, job)
        elif isinstance(definition, Addrmap):
            if job.output.memory_instance is not None:
                raise RecipeError("output.memory_instance requires a memory definition")
            selected = compiler.elaborate(
                top_def_name=job.rdl.definition,
                inst_name=job.output.class_name,
                parameters=dict(job.rdl.parameters),
            ).top
        else:
            raise RecipeError(
                f"RDL definition '{job.rdl.definition}' must exist and be an addrmap or memory"
            )
        if job.base_address + selected.size - 1 > MAX_ADDRESS:
            raise RecipeError("base_address plus RDL aperture exceeds the 64-bit address range")
        buffer = _ExportBuffer(job.output.path)
        UVMExporter().export(
            selected,
            buffer,
            export_as_package=job.output.export_as_package,
            reuse_class_definitions=job.output.reuse_class_definitions,
            use_uvm_factory=job.output.use_uvm_factory,
        )
        generated = "\n".join(
            line.rstrip() for line in buffer.getvalue().splitlines()
        )
        if not re.search(
            rf"^\s*class {re.escape(job.output.class_name)} extends uvm_reg_block;",
            generated, re.MULTILINE,
        ):
            raise RecipeError(
                f"export options cannot honor class_name '{job.output.class_name}'; "
                "disable reuse_class_definitions or use the exported RDL type name"
            )
    except (RecipeError, RDLCompileError, OSError, ValueError) as error:
        detail = str(error).strip() or type(error).__name__
        raise RecipeError(f"interface '{job.name}' failed: {detail}") from error

    content = LICENSE_HEADER + generated.replace("\r\n", "\n")
    if not content.endswith("\n"):
        content += "\n"
    return RenderedOutput(job_name=job.name, path=job.output.path, content=content)


def render_recipe(recipe_path: Path) -> tuple[RenderedOutput, ...]:
    recipe = load_recipe(recipe_path)
    input_paths = {recipe_path.resolve(), *(job.rdl.file for job in recipe.interfaces)}
    outputs = [
        render_interface(job, input_paths=input_paths) for job in recipe.interfaces
    ]
    constants = "\n".join(
        f"    localparam logic [63:0] {job.name.upper()}_BASE_ADDRESS = "
        f"64'h{job.base_address:016x};"
        for job in recipe.interfaces
    )
    config = (
        LICENSE_HEADER
        + f"package {recipe.config_output.stem};\n"
        + constants
        + f"\nendpackage: {recipe.config_output.stem}\n"
    )
    outputs.append(RenderedOutput("configuration", recipe.config_output, config))
    for output in outputs:
        if output.path in input_paths:
            raise RecipeError(f"output conflicts with a recipe or included source: {output.path}")
    return tuple(outputs)


def generate(recipe_path: Path, *, check: bool = False) -> tuple[RenderedOutput, ...]:
    rendered_outputs = render_recipe(recipe_path)
    if check:
        failures: list[str] = []
        for output in rendered_outputs:
            try:
                current = output.path.read_text(encoding="utf-8")
            except FileNotFoundError:
                failures.append(f"missing generated output: {output.path}")
                continue
            except OSError as error:
                failures.append(f"cannot read generated output {output.path}: {error}")
                continue
            if current != output.content:
                failures.append(f"stale generated output: {output.path}")
        if failures:
            raise CheckError("\n".join(failures))
        return rendered_outputs

    for output in rendered_outputs:
        try:
            current = output.path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = None
        except OSError as error:
            raise RecipeError(f"cannot read output {output.path}: {error}") from error
        if current == output.content:
            continue
        try:
            output.path.parent.mkdir(parents=True, exist_ok=True)
            output.path.write_text(output.content, encoding="utf-8", newline="\n")
        except OSError as error:
            raise RecipeError(f"cannot write output {output.path}: {error}") from error
    return rendered_outputs


RECIPE_HELP = """\
INPUTS
  --recipe takes a UTF-8 YAML file using schema_version: 2. Each interface
  names a SystemRDL entry file, an addrmap or mem definition, its parameter
  overrides, and a byte base address. Inputs are RDL, NOT generated SV RAL.
  RDL includes supply dependencies; no SoC map is implicitly loaded.
  Requires PyYAML, systemrdl-compiler, and peakrdl-uvm.

OUTPUTS
  One UVM RAL file per interface at output.path:
    format: package -> .sv package; package name is the filename stem.
    format: include -> .svh header containing classes, not a package.
  One additional .sv package at config_output containing 64-bit constants:
    <UPPERCASE_INTERFACE_NAME>_BASE_ADDRESS
  For example, name: packet produces PACKET_BASE_ADDRESS. Configuration
  package names also come from filename stems. Equal short constant names
  in different packages are distinct; qualify them as package_name::NAME.
  No register RTL, DUT configuration, C headers, or manifests are generated.
  Normal mode renders all outputs, then creates missing output directories
  and writes new/changed files. Identical files are not rewritten. Success
  prints one generated/checked name and path per output; errors go to stderr.

PATH RULES
  --recipe itself is relative to the current working directory.
  ALL paths inside the YAML are relative to the YAML file's directory,
  including input files, include directories, and output files.
  Absolute paths are accepted. YAML paths do not expand ~ or $VARIABLES.
  Include directories are searched in list order, then relative to the RDL
  file containing the include.

YAML SCHEMA
  Required root keys:
    schema_version         Integer 2. Version 1 is rejected.
    config_output          Path to the generated configuration package (.sv).
    interfaces             Non-empty list of interface mappings.

  Required keys in each interfaces entry:
    name                   Unique identifier; determines the base constant.
    rdl                    Input mapping described below.
    base_address           Unsigned 64-bit integer BYTE address, e.g. 0x1000.
    output                 Output mapping described below.

  rdl mapping:
    file                   Required path to an existing SystemRDL entry file.
    definition             Required top-level addrmap or mem type identifier,
                           not an instance path or a generated RAL class.
    parameters             Required {PARAMETER_NAME: value, ...} mapping.
                           Use {} to keep the RDL definition's defaults.
                           Names/types must match that component definition.
    include_paths          Optional list of existing directories; default [].
    defines                Optional {MACRO_NAME: value, ...}; default {}.
                           Integer values become decimal text; booleans
                           become "1"/"0"; strings are passed as macro text.

  output mapping:
    path                   Required output filename; suffix must match format.
    class_name             Required generated top-level UVM block class name.
    format                 Optional "package" (default) or "include".
    reuse_class_definitions
                           Optional boolean; default false. If true, RDL
                           type-based naming must still honor class_name,
                           otherwise generation fails.
    use_uvm_factory        Optional boolean; default false (direct new()).
    memory_instance        Optional member name for a standalone mem;
                           default "memory". Invalid for addrmap inputs.
                           Its wrapper uses class_name, which must not clash
                           with an existing definition in the compiled RDL.

VALUE RULES AND ERRORS
  Identifiers: [A-Za-z_][A-Za-z0-9_]*. Generated class/member names and output
  filename stems must not be SystemVerilog keywords (e.g. class or package).
  Parameters accept scalar unsigned 64-bit integers, booleans, or strings;
  defines accept scalar integers, booleans, or strings. No lists, nested
  mappings, floats, or null values are accepted as parameter/define values.
  Use YAML numbers for integers (512 or 0x200), true/false for booleans,
  and quoted strings for text. A quoted "512" is a string, not an integer.
  Boolean output options must be true/false, not 0/1 or quoted strings.
  Integer parameters and base_address range from 0 to 18446744073709551615.
  base_address cannot be a boolean, string, float, negative value, or null.
  The entire RDL address aperture must fit the 64-bit address range.
  Unknown keys, duplicate YAML keys, interface/base-symbol collisions,
  duplicate package/class names or include guards, and conflicting output
  paths are errors. Outputs must not overwrite the recipe or any RDL input,
  including included files. Interface names differing only by case collide.
  Old exports/sources/top/select/memory_wrapper recipes must be migrated to
  the interface schema above; legacy fields are not silently ignored.

ADDRESS AND MEMORY BEHAVIOR
  RAL child blocks remain zero-based; base_address is emitted in the separate
  configuration package, NOT added to the generated register offsets.
  The consuming testbench must apply each base exactly once at its root map
  and check that the address aperture fits its physical bus. Independent
  interfaces may share a base. The generator does not connect bus agents,
  relocate hardware, set DUT parameters, or add address translation.
  Parameter values go to the compiler as values, not evaluated expressions.
  Standalone mem inputs get a temporary RDL addrmap wrapper before
  elaboration/export. The wrapper is cleaned up, including in --check mode.
  Memory width, depth, access properties, and virtual registers come from
  the configured local definition; each interface gets its own model.

EXAMPLE RDL (save as example/device.rdl)
  addrmap device_regs #(longint unsigned COUNT = 2) {
      reg {
          field { sw = rw; hw = r; } value[31:0];
      } control[COUNT] @ 0x0 += 4;
  };
  mem packet_memory #(longint unsigned ROWS = 512) {
      mementries = ROWS;
      memwidth = 64;
      sw = rw;
  };

EXAMPLE YAML (save as example/recipe.yml)
  schema_version: 2
  config_output: generated/example_config_pkg.sv
  interfaces:
    - name: csr
      rdl:
        file: device.rdl
        definition: device_regs
        parameters: {COUNT: 2}
        include_paths: []
        defines: {}
      base_address: 0x1000
      output:
        path: generated/csr_ral_pkg.sv
        class_name: csr_ral
        format: package
        reuse_class_definitions: false
        use_uvm_factory: false
    - name: packet
      rdl:
        file: device.rdl
        definition: packet_memory
        parameters: {ROWS: 512}
      base_address: 0x2000
      output:
        path: generated/packet_ral_pkg.sv
        class_name: packet_ral
        memory_instance: storage

RUN THE EXAMPLE (from the repository root)
  python3 tools/scripts/gen_ral.py --recipe example/recipe.yml
  python3 tools/scripts/gen_ral.py --recipe example/recipe.yml --check

  Creates these files under example/generated/:
    csr_ral_pkg.sv          Package containing the csr_ral block.
    packet_ral_pkg.sv       Package with packet_ral.storage.m_mem hierarchy.
    example_config_pkg.sv   CSR_BASE_ADDRESS=0x1000,
                           PACKET_BASE_ADDRESS=0x2000.
  To use existing USB inputs instead, pass:
    --recipe src/usb/rdl/ral_exports.yml

EXIT STATUS
  0  Generation succeeded, --check matched every output, or help was shown.
  1  Invalid recipe/RDL, generation/I/O failure, or missing/stale output
     detected by --check.
  2  Invalid command-line arguments (for example, missing --recipe).
  --check still compiles/elaborates inputs and renders all expected outputs,
  but does not create output directories or write model/configuration files.
"""


def _build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate independent UVM RAL models and a base-address configuration\n"
            "package from a schema-version-2 YAML recipe and local SystemRDL inputs."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=RECIPE_HELP,
    )
    parser.add_argument(
        "--recipe",
        type=Path,
        required=True,
        metavar="YAML",
        help="required schema-version-2 YAML recipe; full format and examples below",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="check every expected output without rewriting it; exit 1 if missing/stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_argument_parser().parse_args(argv)
    try:
        outputs = generate(args.recipe, check=args.check)
    except RecipeError as error:
        print(f"gen_ral.py: error: {error}", file=sys.stderr)
        return 1

    action = "checked" if args.check else "generated"
    for output in outputs:
        print(f"{action} {output.job_name}: {output.path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
