---
provides: [ss_asserts]
schema_version: 2.4.0
requires:
  #- caliptra_ss_lc_ctrl_pkg
  #- caliptra_ss_top_defines
  #- axi_mem_pkg
  #- caliptra_ss_top
  #- lc_ctrl
  #- ast_pkg
  - fuse_ctrl_pkg
  - caliptra_top_tb_pkg
targets:
  tb:
    directories: [$COMPILE_ROOT]
    files:
      - $COMPILE_ROOT/caliptra_ss_top_sva.sv
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
