// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef FUSE_CTRL_MMAP_HEADERS
#define FUSE_CTRL_MMAP_HEADERS

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    // SW_TEST_UNLOCK_PARTITION
    CPTRA_SS_MANUF_DEBUG_UNLOCK_TOKEN = 0x0000,
    // SECRET_MANUF_PARTITION
    CPTRA_CORE_UDS_SEED = 0x0048,
    // SECRET_PROD_PARTITION_0
    CPTRA_CORE_FIELD_ENTROPY_0 = 0x0098,
    // SECRET_PROD_PARTITION_1
    CPTRA_CORE_FIELD_ENTROPY_1 = 0x00B0,
    // SECRET_PROD_PARTITION_2
    CPTRA_CORE_FIELD_ENTROPY_2 = 0x00C8,
    // SECRET_PROD_PARTITION_3
    CPTRA_CORE_FIELD_ENTROPY_3 = 0x00E0,
    // SW_MANUF_PARTITION
    CPTRA_CORE_ANTI_ROLLBACK_DISABLE = 0x00F8,
    CPTRA_CORE_IDEVID_CERT_IDEVID_ATTR = 0x00FC,
    SOC_SPECIFIC_IDEVID_CERTIFICATE = 0x015C,
    CPTRA_CORE_IDEVID_MANUF_HSM_IDENTIFIER = 0x0160,
    CPTRA_CORE_SOC_STEPPING_ID = 0x0170,
    // PROD_DEBUG_UNLOCK_MANUF_PARTITION
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_0 = 0x0180,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_1 = 0x01B0,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_2 = 0x01E0,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_3 = 0x0210,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_4 = 0x0240,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_5 = 0x0270,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_6 = 0x02A0,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_7 = 0x02D0,
    // SECRET_LC_TRANSITION_PARTITION
    CPTRA_SS_TEST_UNLOCK_TOKEN_1 = 0x0310,
    CPTRA_SS_TEST_UNLOCK_TOKEN_2 = 0x0320,
    CPTRA_SS_TEST_UNLOCK_TOKEN_3 = 0x0330,
    CPTRA_SS_TEST_UNLOCK_TOKEN_4 = 0x0340,
    CPTRA_SS_TEST_UNLOCK_TOKEN_5 = 0x0350,
    CPTRA_SS_TEST_UNLOCK_TOKEN_6 = 0x0360,
    CPTRA_SS_TEST_UNLOCK_TOKEN_7 = 0x0370,
    CPTRA_SS_TEST_EXIT_TO_MANUF_TOKEN = 0x0380,
    CPTRA_SS_MANUF_TO_PROD_TOKEN = 0x0390,
    CPTRA_SS_PROD_TO_PROD_END_TOKEN = 0x03A0,
    CPTRA_SS_RMA_TOKEN = 0x03B0,
    // SVN_PARTITION
    CPTRA_CORE_FMC_KEY_MANIFEST_SVN = 0x03C8,
    CPTRA_CORE_RUNTIME_SVN = 0x03CC,
    CPTRA_CORE_SOC_MANIFEST_SVN = 0x03DC,
    CPTRA_CORE_SOC_MANIFEST_MAX_SVN = 0x03EC,
    // VENDOR_TEST_PARTITION
    VENDOR_TEST = 0x03F0,
    // VENDOR_HASHES_MANUF_PARTITION
    CPTRA_CORE_VENDOR_PK_HASH_0 = 0x0430,
    CPTRA_CORE_PQC_KEY_TYPE_0 = 0x0460,
    // VENDOR_HASHES_PROD_PARTITION
    CPTRA_SS_OWNER_PK_HASH = 0x0470,
    CPTRA_SS_OWNER_PQC_KEY_TYPE = 0x04A0,
    CPTRA_SS_OWNER_PK_HASH_VALID = 0x04A4,
    CPTRA_CORE_VENDOR_PK_HASH_1 = 0x04A8,
    CPTRA_CORE_PQC_KEY_TYPE_1 = 0x04D8,
    CPTRA_CORE_VENDOR_PK_HASH_2 = 0x04DC,
    CPTRA_CORE_PQC_KEY_TYPE_2 = 0x050C,
    CPTRA_CORE_VENDOR_PK_HASH_3 = 0x0510,
    CPTRA_CORE_PQC_KEY_TYPE_3 = 0x0540,
    CPTRA_CORE_VENDOR_PK_HASH_4 = 0x0544,
    CPTRA_CORE_PQC_KEY_TYPE_4 = 0x0574,
    CPTRA_CORE_VENDOR_PK_HASH_5 = 0x0578,
    CPTRA_CORE_PQC_KEY_TYPE_5 = 0x05A8,
    CPTRA_CORE_VENDOR_PK_HASH_6 = 0x05AC,
    CPTRA_CORE_PQC_KEY_TYPE_6 = 0x05DC,
    CPTRA_CORE_VENDOR_PK_HASH_7 = 0x05E0,
    CPTRA_CORE_PQC_KEY_TYPE_7 = 0x0610,
    CPTRA_CORE_VENDOR_PK_HASH_8 = 0x0614,
    CPTRA_CORE_PQC_KEY_TYPE_8 = 0x0644,
    CPTRA_CORE_VENDOR_PK_HASH_9 = 0x0648,
    CPTRA_CORE_PQC_KEY_TYPE_9 = 0x0678,
    CPTRA_CORE_VENDOR_PK_HASH_10 = 0x067C,
    CPTRA_CORE_PQC_KEY_TYPE_10 = 0x06AC,
    CPTRA_CORE_VENDOR_PK_HASH_11 = 0x06B0,
    CPTRA_CORE_PQC_KEY_TYPE_11 = 0x06E0,
    CPTRA_CORE_VENDOR_PK_HASH_12 = 0x06E4,
    CPTRA_CORE_PQC_KEY_TYPE_12 = 0x0714,
    CPTRA_CORE_VENDOR_PK_HASH_13 = 0x0718,
    CPTRA_CORE_PQC_KEY_TYPE_13 = 0x0748,
    CPTRA_CORE_VENDOR_PK_HASH_14 = 0x074C,
    CPTRA_CORE_PQC_KEY_TYPE_14 = 0x077C,
    CPTRA_CORE_VENDOR_PK_HASH_15 = 0x0780,
    CPTRA_CORE_PQC_KEY_TYPE_15 = 0x07B0,
    CPTRA_CORE_VENDOR_PK_HASH_VALID = 0x07B4,
    // VENDOR_REVOCATIONS_PROD_PARTITION
    CPTRA_SS_OWNER_ECC_REVOCATION = 0x07D0,
    CPTRA_SS_OWNER_LMS_REVOCATION = 0x07D4,
    CPTRA_SS_OWNER_MLDSA_REVOCATION = 0x07D8,
    CPTRA_CORE_ECC_REVOCATION_0 = 0x07DC,
    CPTRA_CORE_LMS_REVOCATION_0 = 0x07E0,
    CPTRA_CORE_MLDSA_REVOCATION_0 = 0x07E4,
    CPTRA_CORE_ECC_REVOCATION_1 = 0x07E8,
    CPTRA_CORE_LMS_REVOCATION_1 = 0x07EC,
    CPTRA_CORE_MLDSA_REVOCATION_1 = 0x07F0,
    CPTRA_CORE_ECC_REVOCATION_2 = 0x07F4,
    CPTRA_CORE_LMS_REVOCATION_2 = 0x07F8,
    CPTRA_CORE_MLDSA_REVOCATION_2 = 0x07FC,
    CPTRA_CORE_ECC_REVOCATION_3 = 0x0800,
    CPTRA_CORE_LMS_REVOCATION_3 = 0x0804,
    CPTRA_CORE_MLDSA_REVOCATION_3 = 0x0808,
    CPTRA_CORE_ECC_REVOCATION_4 = 0x080C,
    CPTRA_CORE_LMS_REVOCATION_4 = 0x0810,
    CPTRA_CORE_MLDSA_REVOCATION_4 = 0x0814,
    CPTRA_CORE_ECC_REVOCATION_5 = 0x0818,
    CPTRA_CORE_LMS_REVOCATION_5 = 0x081C,
    CPTRA_CORE_MLDSA_REVOCATION_5 = 0x0820,
    CPTRA_CORE_ECC_REVOCATION_6 = 0x0824,
    CPTRA_CORE_LMS_REVOCATION_6 = 0x0828,
    CPTRA_CORE_MLDSA_REVOCATION_6 = 0x082C,
    CPTRA_CORE_ECC_REVOCATION_7 = 0x0830,
    CPTRA_CORE_LMS_REVOCATION_7 = 0x0834,
    CPTRA_CORE_MLDSA_REVOCATION_7 = 0x0838,
    CPTRA_CORE_ECC_REVOCATION_8 = 0x083C,
    CPTRA_CORE_LMS_REVOCATION_8 = 0x0840,
    CPTRA_CORE_MLDSA_REVOCATION_8 = 0x0844,
    CPTRA_CORE_ECC_REVOCATION_9 = 0x0848,
    CPTRA_CORE_LMS_REVOCATION_9 = 0x084C,
    CPTRA_CORE_MLDSA_REVOCATION_9 = 0x0850,
    CPTRA_CORE_ECC_REVOCATION_10 = 0x0854,
    CPTRA_CORE_LMS_REVOCATION_10 = 0x0858,
    CPTRA_CORE_MLDSA_REVOCATION_10 = 0x085C,
    CPTRA_CORE_ECC_REVOCATION_11 = 0x0860,
    CPTRA_CORE_LMS_REVOCATION_11 = 0x0864,
    CPTRA_CORE_MLDSA_REVOCATION_11 = 0x0868,
    CPTRA_CORE_ECC_REVOCATION_12 = 0x086C,
    CPTRA_CORE_LMS_REVOCATION_12 = 0x0870,
    CPTRA_CORE_MLDSA_REVOCATION_12 = 0x0874,
    CPTRA_CORE_ECC_REVOCATION_13 = 0x0878,
    CPTRA_CORE_LMS_REVOCATION_13 = 0x087C,
    CPTRA_CORE_MLDSA_REVOCATION_13 = 0x0880,
    CPTRA_CORE_ECC_REVOCATION_14 = 0x0884,
    CPTRA_CORE_LMS_REVOCATION_14 = 0x0888,
    CPTRA_CORE_MLDSA_REVOCATION_14 = 0x088C,
    CPTRA_CORE_ECC_REVOCATION_15 = 0x0890,
    CPTRA_CORE_LMS_REVOCATION_15 = 0x0894,
    CPTRA_CORE_MLDSA_REVOCATION_15 = 0x0898,
    // VENDOR_SECRET_PROD_PARTITION
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_0 = 0x08A8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_1 = 0x08C8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_2 = 0x08E8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_3 = 0x0908,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_4 = 0x0928,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_5 = 0x0948,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_6 = 0x0968,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_7 = 0x0988,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_8 = 0x09A8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_9 = 0x09C8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_10 = 0x09E8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_11 = 0x0A08,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_12 = 0x0A28,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_13 = 0x0A48,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_14 = 0x0A68,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_15 = 0x0A88,
    // VENDOR_NON_SECRET_PROD_PARTITION
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_0 = 0x0AB8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_1 = 0x0AD8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_2 = 0x0AF8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_3 = 0x0B18,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_4 = 0x0B38,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_5 = 0x0B58,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_6 = 0x0B78,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_7 = 0x0B98,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_8 = 0x0BB8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_9 = 0x0BD8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_10 = 0x0BF8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_11 = 0x0C18,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_12 = 0x0C38,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_13 = 0x0C58,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_14 = 0x0C78,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_15 = 0x0C98,
    // CPTRA_SS_LOCK_HEK_PROD_0
    CPTRA_SS_LOCK_HEK_PROD_0_RATCHET_SEED = 0x0CC0,
    // CPTRA_SS_LOCK_HEK_PROD_1
    CPTRA_SS_LOCK_HEK_PROD_1_RATCHET_SEED = 0x0CF0,
    // CPTRA_SS_LOCK_HEK_PROD_2
    CPTRA_SS_LOCK_HEK_PROD_2_RATCHET_SEED = 0x0D20,
    // CPTRA_SS_LOCK_HEK_PROD_3
    CPTRA_SS_LOCK_HEK_PROD_3_RATCHET_SEED = 0x0D50,
    // CPTRA_SS_LOCK_HEK_PROD_4
    CPTRA_SS_LOCK_HEK_PROD_4_RATCHET_SEED = 0x0D80,
    // CPTRA_SS_LOCK_HEK_PROD_5
    CPTRA_SS_LOCK_HEK_PROD_5_RATCHET_SEED = 0x0DB0,
    // CPTRA_SS_LOCK_HEK_PROD_6
    CPTRA_SS_LOCK_HEK_PROD_6_RATCHET_SEED = 0x0DE0,
    // LIFE_CYCLE
    LC_TRANSITION_CNT = 0x0E10,
    LC_STATE = 0x0E40
} fuse_k;

typedef enum {
    SW_TEST_UNLOCK_PARTITION,
    SECRET_MANUF_PARTITION,
    SECRET_PROD_PARTITION_0,
    SECRET_PROD_PARTITION_1,
    SECRET_PROD_PARTITION_2,
    SECRET_PROD_PARTITION_3,
    SW_MANUF_PARTITION,
    PROD_DEBUG_UNLOCK_MANUF_PARTITION,
    SECRET_LC_TRANSITION_PARTITION,
    SVN_PARTITION,
    VENDOR_TEST_PARTITION,
    VENDOR_HASHES_MANUF_PARTITION,
    VENDOR_HASHES_PROD_PARTITION,
    VENDOR_REVOCATIONS_PROD_PARTITION,
    VENDOR_SECRET_PROD_PARTITION,
    VENDOR_NON_SECRET_PROD_PARTITION,
    CPTRA_SS_LOCK_HEK_PROD_0,
    CPTRA_SS_LOCK_HEK_PROD_1,
    CPTRA_SS_LOCK_HEK_PROD_2,
    CPTRA_SS_LOCK_HEK_PROD_3,
    CPTRA_SS_LOCK_HEK_PROD_4,
    CPTRA_SS_LOCK_HEK_PROD_5,
    CPTRA_SS_LOCK_HEK_PROD_6,
    LIFE_CYCLE
} partition_k;

typedef struct {
    uint32_t        index;
    uint32_t        address;
    uint32_t        digest_address;
    uint32_t        zer_address;
    uint32_t        variant;
    uint32_t        granularity;
    bool            is_secret;
    bool            hw_digest;
    bool            sw_digest;
    bool            has_ecc;
    uint32_t        lc_phase;
    bool            is_lifecycle;
    // The number of fuses in the partition. Note that this may be
    // larger than the number of fuses explictly specified in the
    // hjson. Any digest or zeroization field is also added to the
    // list.
    uint32_t        num_fuses;
    const uint32_t *fuses;
} partition_t;

#define NUM_PARTITIONS 24

// A map of the NUM_PARTITIONS fuse partitions.
extern const partition_t partitions[];

// Arrays with indices of fuses for each partition.
extern const uint32_t sw_test_unlock_partition_fuses[];
extern const uint32_t secret_manuf_partition_fuses[];
extern const uint32_t secret_prod_partition_0_fuses[];
extern const uint32_t secret_prod_partition_1_fuses[];
extern const uint32_t secret_prod_partition_2_fuses[];
extern const uint32_t secret_prod_partition_3_fuses[];
extern const uint32_t sw_manuf_partition_fuses[];
extern const uint32_t prod_debug_unlock_manuf_partition_fuses[];
extern const uint32_t secret_lc_transition_partition_fuses[];
extern const uint32_t svn_partition_fuses[];
extern const uint32_t vendor_test_partition_fuses[];
extern const uint32_t vendor_hashes_manuf_partition_fuses[];
extern const uint32_t vendor_hashes_prod_partition_fuses[];
extern const uint32_t vendor_revocations_prod_partition_fuses[];
extern const uint32_t vendor_secret_prod_partition_fuses[];
extern const uint32_t vendor_non_secret_prod_partition_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_0_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_1_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_2_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_3_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_4_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_5_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_6_fuses[];
extern const uint32_t life_cycle_fuses[];

#endif // FUSE_CTRL_MMAP_HEADERS
