// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef FUSE_CTRL_ADDRMAP_HEADER
#define FUSE_CTRL_ADDRMAP_HEADER

#define FUSE_CTRL_BASE_ADDR (0x70000000)

#define FUSE_CTRL_INTR_STATE                                                  (FUSE_CTRL_BASE_ADDR + 0x000)
#define FUSE_CTRL_INTR_ENABLE                                                 (FUSE_CTRL_BASE_ADDR + 0x004)
#define FUSE_CTRL_INTR_TEST                                                   (FUSE_CTRL_BASE_ADDR + 0x008)
#define FUSE_CTRL_ALERT_TEST                                                  (FUSE_CTRL_BASE_ADDR + 0x00C)
#define FUSE_CTRL_STATUS                                                      (FUSE_CTRL_BASE_ADDR + 0x010)
#define FUSE_CTRL_ERR_CODE_0                                                  (FUSE_CTRL_BASE_ADDR + 0x014)
#define FUSE_CTRL_ERR_CODE_1                                                  (FUSE_CTRL_BASE_ADDR + 0x018)
#define FUSE_CTRL_ERR_CODE_2                                                  (FUSE_CTRL_BASE_ADDR + 0x01C)
#define FUSE_CTRL_ERR_CODE_3                                                  (FUSE_CTRL_BASE_ADDR + 0x020)
#define FUSE_CTRL_ERR_CODE_4                                                  (FUSE_CTRL_BASE_ADDR + 0x024)
#define FUSE_CTRL_ERR_CODE_5                                                  (FUSE_CTRL_BASE_ADDR + 0x028)
#define FUSE_CTRL_ERR_CODE_6                                                  (FUSE_CTRL_BASE_ADDR + 0x02C)
#define FUSE_CTRL_ERR_CODE_7                                                  (FUSE_CTRL_BASE_ADDR + 0x030)
#define FUSE_CTRL_ERR_CODE_8                                                  (FUSE_CTRL_BASE_ADDR + 0x034)
#define FUSE_CTRL_ERR_CODE_9                                                  (FUSE_CTRL_BASE_ADDR + 0x038)
#define FUSE_CTRL_ERR_CODE_10                                                 (FUSE_CTRL_BASE_ADDR + 0x03C)
#define FUSE_CTRL_ERR_CODE_11                                                 (FUSE_CTRL_BASE_ADDR + 0x040)
#define FUSE_CTRL_ERR_CODE_12                                                 (FUSE_CTRL_BASE_ADDR + 0x044)
#define FUSE_CTRL_ERR_CODE_13                                                 (FUSE_CTRL_BASE_ADDR + 0x048)
#define FUSE_CTRL_ERR_CODE_14                                                 (FUSE_CTRL_BASE_ADDR + 0x04C)
#define FUSE_CTRL_ERR_CODE_15                                                 (FUSE_CTRL_BASE_ADDR + 0x050)
#define FUSE_CTRL_ERR_CODE_16                                                 (FUSE_CTRL_BASE_ADDR + 0x054)
#define FUSE_CTRL_ERR_CODE_17                                                 (FUSE_CTRL_BASE_ADDR + 0x058)
#define FUSE_CTRL_DIRECT_ACCESS_REGWEN                                        (FUSE_CTRL_BASE_ADDR + 0x05C)
#define FUSE_CTRL_DIRECT_ACCESS_CMD                                           (FUSE_CTRL_BASE_ADDR + 0x060)
#define FUSE_CTRL_DIRECT_ACCESS_ADDRESS                                       (FUSE_CTRL_BASE_ADDR + 0x064)
#define FUSE_CTRL_DIRECT_ACCESS_WDATA_0                                       (FUSE_CTRL_BASE_ADDR + 0x068)
#define FUSE_CTRL_DIRECT_ACCESS_WDATA_1                                       (FUSE_CTRL_BASE_ADDR + 0x06C)
#define FUSE_CTRL_DIRECT_ACCESS_RDATA_0                                       (FUSE_CTRL_BASE_ADDR + 0x070)
#define FUSE_CTRL_DIRECT_ACCESS_RDATA_1                                       (FUSE_CTRL_BASE_ADDR + 0x074)
#define FUSE_CTRL_CHECK_TRIGGER_REGWEN                                        (FUSE_CTRL_BASE_ADDR + 0x078)
#define FUSE_CTRL_CHECK_TRIGGER                                               (FUSE_CTRL_BASE_ADDR + 0x07C)
#define FUSE_CTRL_CHECK_REGWEN                                                (FUSE_CTRL_BASE_ADDR + 0x080)
#define FUSE_CTRL_CHECK_TIMEOUT                                               (FUSE_CTRL_BASE_ADDR + 0x084)
#define FUSE_CTRL_INTEGRITY_CHECK_PERIOD                                      (FUSE_CTRL_BASE_ADDR + 0x088)
#define FUSE_CTRL_CONSISTENCY_CHECK_PERIOD                                    (FUSE_CTRL_BASE_ADDR + 0x08C)
#define FUSE_CTRL_SW_MANUF_PARTITION_READ_LOCK                                (FUSE_CTRL_BASE_ADDR + 0x090)
#define FUSE_CTRL_SVN_PARTITION_READ_LOCK                                     (FUSE_CTRL_BASE_ADDR + 0x094)
#define FUSE_CTRL_VENDOR_TEST_PARTITION_READ_LOCK                             (FUSE_CTRL_BASE_ADDR + 0x098)
#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_READ_LOCK                     (FUSE_CTRL_BASE_ADDR + 0x09C)
#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_READ_LOCK                      (FUSE_CTRL_BASE_ADDR + 0x0A0)
#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_READ_LOCK                 (FUSE_CTRL_BASE_ADDR + 0x0A4)
#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_READ_LOCK                  (FUSE_CTRL_BASE_ADDR + 0x0A8)
#define FUSE_CTRL_ZEROIZE_REGWEN                                              (FUSE_CTRL_BASE_ADDR + 0x0AC)
#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_ZEROIZE                      (FUSE_CTRL_BASE_ADDR + 0x0B0)
#define FUSE_CTRL_VENDOR_PK_HASH_VOLATILE_LOCK                                (FUSE_CTRL_BASE_ADDR + 0x0B4)
#define FUSE_CTRL_SW_TEST_UNLOCK_PARTITION_DIGEST_0                           (FUSE_CTRL_BASE_ADDR + 0x0B8)
#define FUSE_CTRL_SW_TEST_UNLOCK_PARTITION_DIGEST_1                           (FUSE_CTRL_BASE_ADDR + 0x0BC)
#define FUSE_CTRL_SECRET_MANUF_PARTITION_DIGEST_0                             (FUSE_CTRL_BASE_ADDR + 0x0C0)
#define FUSE_CTRL_SECRET_MANUF_PARTITION_DIGEST_1                             (FUSE_CTRL_BASE_ADDR + 0x0C4)
#define FUSE_CTRL_SECRET_PROD_PARTITION_0_DIGEST_0                            (FUSE_CTRL_BASE_ADDR + 0x0C8)
#define FUSE_CTRL_SECRET_PROD_PARTITION_0_DIGEST_1                            (FUSE_CTRL_BASE_ADDR + 0x0CC)
#define FUSE_CTRL_SECRET_PROD_PARTITION_1_DIGEST_0                            (FUSE_CTRL_BASE_ADDR + 0x0D0)
#define FUSE_CTRL_SECRET_PROD_PARTITION_1_DIGEST_1                            (FUSE_CTRL_BASE_ADDR + 0x0D4)
#define FUSE_CTRL_SECRET_PROD_PARTITION_2_DIGEST_0                            (FUSE_CTRL_BASE_ADDR + 0x0D8)
#define FUSE_CTRL_SECRET_PROD_PARTITION_2_DIGEST_1                            (FUSE_CTRL_BASE_ADDR + 0x0DC)
#define FUSE_CTRL_SECRET_PROD_PARTITION_3_DIGEST_0                            (FUSE_CTRL_BASE_ADDR + 0x0E0)
#define FUSE_CTRL_SECRET_PROD_PARTITION_3_DIGEST_1                            (FUSE_CTRL_BASE_ADDR + 0x0E4)
#define FUSE_CTRL_SW_MANUF_PARTITION_DIGEST_0                                 (FUSE_CTRL_BASE_ADDR + 0x0E8)
#define FUSE_CTRL_SW_MANUF_PARTITION_DIGEST_1                                 (FUSE_CTRL_BASE_ADDR + 0x0EC)
#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_DIGEST_0                     (FUSE_CTRL_BASE_ADDR + 0x0F0)
#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_DIGEST_1                     (FUSE_CTRL_BASE_ADDR + 0x0F4)
#define FUSE_CTRL_VENDOR_TEST_PARTITION_DIGEST_0                              (FUSE_CTRL_BASE_ADDR + 0x0F8)
#define FUSE_CTRL_VENDOR_TEST_PARTITION_DIGEST_1                              (FUSE_CTRL_BASE_ADDR + 0x0FC)
#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_DIGEST_0                      (FUSE_CTRL_BASE_ADDR + 0x100)
#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_DIGEST_1                      (FUSE_CTRL_BASE_ADDR + 0x104)
#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_DIGEST_0                       (FUSE_CTRL_BASE_ADDR + 0x108)
#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_DIGEST_1                       (FUSE_CTRL_BASE_ADDR + 0x10C)
#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_DIGEST_0                  (FUSE_CTRL_BASE_ADDR + 0x110)
#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_DIGEST_1                  (FUSE_CTRL_BASE_ADDR + 0x114)
#define FUSE_CTRL_VENDOR_SECRET_PROD_PARTITION_DIGEST_0                       (FUSE_CTRL_BASE_ADDR + 0x118)
#define FUSE_CTRL_VENDOR_SECRET_PROD_PARTITION_DIGEST_1                       (FUSE_CTRL_BASE_ADDR + 0x11C)
#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_DIGEST_0                   (FUSE_CTRL_BASE_ADDR + 0x120)
#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_DIGEST_1                   (FUSE_CTRL_BASE_ADDR + 0x124)

#define FUSE_CTRL_INTR_STATE_WIDTH (2)
#define FUSE_CTRL_INTR_STATE_OTP_OPERATION_DONE_WIDTH (1)
#define FUSE_CTRL_INTR_STATE_OTP_OPERATION_DONE_OFFSET (0)
#define FUSE_CTRL_INTR_STATE_OTP_OPERATION_DONE_MASK (1)
#define FUSE_CTRL_INTR_STATE_OTP_ERROR_WIDTH (1)
#define FUSE_CTRL_INTR_STATE_OTP_ERROR_OFFSET (1)
#define FUSE_CTRL_INTR_STATE_OTP_ERROR_MASK (2)

#define FUSE_CTRL_INTR_ENABLE_WIDTH (2)
#define FUSE_CTRL_INTR_ENABLE_OTP_OPERATION_DONE_WIDTH (1)
#define FUSE_CTRL_INTR_ENABLE_OTP_OPERATION_DONE_OFFSET (0)
#define FUSE_CTRL_INTR_ENABLE_OTP_OPERATION_DONE_MASK (1)
#define FUSE_CTRL_INTR_ENABLE_OTP_ERROR_WIDTH (1)
#define FUSE_CTRL_INTR_ENABLE_OTP_ERROR_OFFSET (1)
#define FUSE_CTRL_INTR_ENABLE_OTP_ERROR_MASK (2)

#define FUSE_CTRL_INTR_TEST_WIDTH (2)
#define FUSE_CTRL_INTR_TEST_OTP_OPERATION_DONE_WIDTH (1)
#define FUSE_CTRL_INTR_TEST_OTP_OPERATION_DONE_OFFSET (0)
#define FUSE_CTRL_INTR_TEST_OTP_OPERATION_DONE_MASK (1)
#define FUSE_CTRL_INTR_TEST_OTP_ERROR_WIDTH (1)
#define FUSE_CTRL_INTR_TEST_OTP_ERROR_OFFSET (1)
#define FUSE_CTRL_INTR_TEST_OTP_ERROR_MASK (2)

#define FUSE_CTRL_ALERT_TEST_WIDTH (5)
#define FUSE_CTRL_ALERT_TEST_FATAL_MACRO_ERROR_WIDTH (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_MACRO_ERROR_OFFSET (0)
#define FUSE_CTRL_ALERT_TEST_FATAL_MACRO_ERROR_MASK (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_CHECK_ERROR_WIDTH (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_CHECK_ERROR_OFFSET (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_CHECK_ERROR_MASK (2)
#define FUSE_CTRL_ALERT_TEST_FATAL_BUS_INTEG_ERROR_WIDTH (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_BUS_INTEG_ERROR_OFFSET (2)
#define FUSE_CTRL_ALERT_TEST_FATAL_BUS_INTEG_ERROR_MASK (4)
#define FUSE_CTRL_ALERT_TEST_FATAL_PRIM_OTP_ALERT_WIDTH (1)
#define FUSE_CTRL_ALERT_TEST_FATAL_PRIM_OTP_ALERT_OFFSET (3)
#define FUSE_CTRL_ALERT_TEST_FATAL_PRIM_OTP_ALERT_MASK (8)
#define FUSE_CTRL_ALERT_TEST_RECOV_PRIM_OTP_ALERT_WIDTH (1)
#define FUSE_CTRL_ALERT_TEST_RECOV_PRIM_OTP_ALERT_OFFSET (4)
#define FUSE_CTRL_ALERT_TEST_RECOV_PRIM_OTP_ALERT_MASK (16)

#define FUSE_CTRL_STATUS_WIDTH (24)
#define FUSE_CTRL_STATUS_SW_TEST_UNLOCK_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SW_TEST_UNLOCK_PARTITION_ERROR_OFFSET (0)
#define FUSE_CTRL_STATUS_SW_TEST_UNLOCK_PARTITION_ERROR_MASK (1)
#define FUSE_CTRL_STATUS_SECRET_MANUF_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_MANUF_PARTITION_ERROR_OFFSET (1)
#define FUSE_CTRL_STATUS_SECRET_MANUF_PARTITION_ERROR_MASK (2)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_0_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_0_ERROR_OFFSET (2)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_0_ERROR_MASK (4)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_1_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_1_ERROR_OFFSET (3)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_1_ERROR_MASK (8)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_2_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_2_ERROR_OFFSET (4)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_2_ERROR_MASK (16)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_3_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_3_ERROR_OFFSET (5)
#define FUSE_CTRL_STATUS_SECRET_PROD_PARTITION_3_ERROR_MASK (32)
#define FUSE_CTRL_STATUS_SW_MANUF_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SW_MANUF_PARTITION_ERROR_OFFSET (6)
#define FUSE_CTRL_STATUS_SW_MANUF_PARTITION_ERROR_MASK (64)
#define FUSE_CTRL_STATUS_SECRET_LC_TRANSITION_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SECRET_LC_TRANSITION_PARTITION_ERROR_OFFSET (7)
#define FUSE_CTRL_STATUS_SECRET_LC_TRANSITION_PARTITION_ERROR_MASK (128)
#define FUSE_CTRL_STATUS_SVN_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SVN_PARTITION_ERROR_OFFSET (8)
#define FUSE_CTRL_STATUS_SVN_PARTITION_ERROR_MASK (256)
#define FUSE_CTRL_STATUS_VENDOR_TEST_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_TEST_PARTITION_ERROR_OFFSET (9)
#define FUSE_CTRL_STATUS_VENDOR_TEST_PARTITION_ERROR_MASK (512)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_MANUF_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_MANUF_PARTITION_ERROR_OFFSET (10)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_MANUF_PARTITION_ERROR_MASK (1024)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_PROD_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_PROD_PARTITION_ERROR_OFFSET (11)
#define FUSE_CTRL_STATUS_VENDOR_HASHES_PROD_PARTITION_ERROR_MASK (2048)
#define FUSE_CTRL_STATUS_VENDOR_REVOCATIONS_PROD_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_REVOCATIONS_PROD_PARTITION_ERROR_OFFSET (12)
#define FUSE_CTRL_STATUS_VENDOR_REVOCATIONS_PROD_PARTITION_ERROR_MASK (4096)
#define FUSE_CTRL_STATUS_VENDOR_SECRET_PROD_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_SECRET_PROD_PARTITION_ERROR_OFFSET (13)
#define FUSE_CTRL_STATUS_VENDOR_SECRET_PROD_PARTITION_ERROR_MASK (8192)
#define FUSE_CTRL_STATUS_VENDOR_NON_SECRET_PROD_PARTITION_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_VENDOR_NON_SECRET_PROD_PARTITION_ERROR_OFFSET (14)
#define FUSE_CTRL_STATUS_VENDOR_NON_SECRET_PROD_PARTITION_ERROR_MASK (16384)
#define FUSE_CTRL_STATUS_LIFE_CYCLE_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_LIFE_CYCLE_ERROR_OFFSET (15)
#define FUSE_CTRL_STATUS_LIFE_CYCLE_ERROR_MASK (32768)
#define FUSE_CTRL_STATUS_DAI_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_DAI_ERROR_OFFSET (16)
#define FUSE_CTRL_STATUS_DAI_ERROR_MASK (65536)
#define FUSE_CTRL_STATUS_LCI_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_LCI_ERROR_OFFSET (17)
#define FUSE_CTRL_STATUS_LCI_ERROR_MASK (131072)
#define FUSE_CTRL_STATUS_TIMEOUT_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_TIMEOUT_ERROR_OFFSET (18)
#define FUSE_CTRL_STATUS_TIMEOUT_ERROR_MASK (262144)
#define FUSE_CTRL_STATUS_LFSR_FSM_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_LFSR_FSM_ERROR_OFFSET (19)
#define FUSE_CTRL_STATUS_LFSR_FSM_ERROR_MASK (524288)
#define FUSE_CTRL_STATUS_SCRAMBLING_FSM_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_SCRAMBLING_FSM_ERROR_OFFSET (20)
#define FUSE_CTRL_STATUS_SCRAMBLING_FSM_ERROR_MASK (1048576)
#define FUSE_CTRL_STATUS_BUS_INTEG_ERROR_WIDTH (1)
#define FUSE_CTRL_STATUS_BUS_INTEG_ERROR_OFFSET (21)
#define FUSE_CTRL_STATUS_BUS_INTEG_ERROR_MASK (2097152)
#define FUSE_CTRL_STATUS_DAI_IDLE_WIDTH (1)
#define FUSE_CTRL_STATUS_DAI_IDLE_OFFSET (22)
#define FUSE_CTRL_STATUS_DAI_IDLE_MASK (4194304)
#define FUSE_CTRL_STATUS_CHECK_PENDING_WIDTH (1)
#define FUSE_CTRL_STATUS_CHECK_PENDING_OFFSET (23)
#define FUSE_CTRL_STATUS_CHECK_PENDING_MASK (8388608)

#define FUSE_CTRL_ERR_CODE_0_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_1_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_2_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_3_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_4_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_5_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_6_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_7_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_8_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_9_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_10_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_11_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_12_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_13_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_14_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_15_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_16_WIDTH (3)

#define FUSE_CTRL_ERR_CODE_17_WIDTH (3)

#define FUSE_CTRL_DIRECT_ACCESS_REGWEN_WIDTH (1)

#define FUSE_CTRL_DIRECT_ACCESS_CMD_WIDTH (3)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_RD_WIDTH (1)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_RD_OFFSET (0)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_RD_MASK (1)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_WR_WIDTH (1)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_WR_OFFSET (1)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_WR_MASK (2)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_DIGEST_WIDTH (1)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_DIGEST_OFFSET (2)
#define FUSE_CTRL_DIRECT_ACCESS_CMD_DIGEST_MASK (4)

#define FUSE_CTRL_DIRECT_ACCESS_ADDRESS_WIDTH (12)

#define FUSE_CTRL_DIRECT_ACCESS_WDATA_0_WIDTH (32)

#define FUSE_CTRL_DIRECT_ACCESS_WDATA_1_WIDTH (32)

#define FUSE_CTRL_DIRECT_ACCESS_RDATA_0_WIDTH (32)

#define FUSE_CTRL_DIRECT_ACCESS_RDATA_1_WIDTH (32)

#define FUSE_CTRL_CHECK_TRIGGER_REGWEN_WIDTH (1)

#define FUSE_CTRL_CHECK_TRIGGER_WIDTH (2)
#define FUSE_CTRL_CHECK_TRIGGER_INTEGRITY_WIDTH (1)
#define FUSE_CTRL_CHECK_TRIGGER_INTEGRITY_OFFSET (0)
#define FUSE_CTRL_CHECK_TRIGGER_INTEGRITY_MASK (1)
#define FUSE_CTRL_CHECK_TRIGGER_CONSISTENCY_WIDTH (1)
#define FUSE_CTRL_CHECK_TRIGGER_CONSISTENCY_OFFSET (1)
#define FUSE_CTRL_CHECK_TRIGGER_CONSISTENCY_MASK (2)

#define FUSE_CTRL_CHECK_REGWEN_WIDTH (1)

#define FUSE_CTRL_CHECK_TIMEOUT_WIDTH (32)

#define FUSE_CTRL_INTEGRITY_CHECK_PERIOD_WIDTH (32)

#define FUSE_CTRL_CONSISTENCY_CHECK_PERIOD_WIDTH (32)

#define FUSE_CTRL_SW_MANUF_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_SVN_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_VENDOR_TEST_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_READ_LOCK_WIDTH (1)

#define FUSE_CTRL_ZEROIZE_REGWEN_WIDTH (1)

#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_ZEROIZE_WIDTH (1)

#define FUSE_CTRL_VENDOR_PK_HASH_VOLATILE_LOCK_WIDTH (32)

#define FUSE_CTRL_SW_TEST_UNLOCK_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SW_TEST_UNLOCK_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_MANUF_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_MANUF_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_0_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_0_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_1_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_1_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_2_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_2_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_3_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_PROD_PARTITION_3_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SW_MANUF_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SW_MANUF_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_SECRET_LC_TRANSITION_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_TEST_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_TEST_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_HASHES_MANUF_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_HASHES_PROD_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_REVOCATIONS_PROD_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_SECRET_PROD_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_SECRET_PROD_PARTITION_DIGEST_1_WIDTH (32)

#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_DIGEST_0_WIDTH (32)

#define FUSE_CTRL_VENDOR_NON_SECRET_PROD_PARTITION_DIGEST_1_WIDTH (32)


#endif
