// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// -----------------------------------------------------------------------------
// USBDC1 (device1) variant, generated by tools/scripts/gen_usb_dev_variants.py
// from the USBDC0 source family. Differences from the source:
//   - hub-class port requests target downstream port 2 (USBDC1) instead of
//     port 1 (USBDC0);
//   - the matching firmware is built with -DUSB_DEV_SEL=1 so the shared USB
//     library addresses the USBDC1 register/DMA aperture at 0x2001_0000 /
//     0x2001_0100.
// The bus-level protocol, endpoint configuration and assigned USB device
// address (2) are unchanged - USBDC1 is functionally identical to USBDC0.
// -----------------------------------------------------------------------------
`ifndef CALIPTRA_SS_USB_FS_DEV1_BULK_LOOPBACK_SEQUENCE_SV
`define CALIPTRA_SS_USB_FS_DEV1_BULK_LOOPBACK_SEQUENCE_SV

// =============================================================================
// USB Full-Speed device bulk loopback sequence.
//
// Sequence flow:
//   1. Wait for FS host link to reach ENABLED.
//   2. Issue an explicit USB bus reset (SE0 for tdrst=150us) via the VIP
//      protocol service sequencer. In FS mode with high_speed_capable=0 the
//      SVT VIP host goes directly from attach to ENABLED without driving SE0.
//      The NXP IP_3511HS device controller requires receiving a bus reset to
//      transition from power-on state into DEFAULT state (address=0, EP0 armed,
//      UTMI TX enabled). Without this the DUT never generates ACK or DATA
//      responses and every enumeration transfer ABORTs at the SETUP stage.
//   3. Start SOF generation to keep the FS link alive between transfers.
//   4. Post-reset settling delay for MCU firmware to handle DRES_C and re-arm
//      EP0 buffers.
//   5. Full enumeration (GET_DESC/GET_STATUS/SET_ADDRESS/GET_DESC/
//      GET_CONFIG/SET_CONFIG/GET_CONFIG verify).
//      Each control transfer uses finish_item then a separate wait_xfer_done
//      call -- the same sequential pattern used by the working init and
//      hs_dev_bulk_out sequences. Do NOT fork NOTIFY_USB_TRANSFER_ENDED inside
//      finish_item; the trigger is level-sticky in SVT and wait_trigger works
//      correctly when called after finish_item returns.
//   6. Send 64 bytes of bulk OUT data to EP1 (byte pattern i=0..63).
//      NOTIFY wait is forked BEFORE finish_item for bulk transfers only because
//      a single 64-byte FS packet can complete within the same delta-cycle
//      window as finish_item and the trigger would be missed.
//   7. Read 64 bytes back from EP1 IN (loopback).
//   8. Verify loopback data matches sent bytes.
//   9. Allow MCU firmware time to complete loopback and log result.
// =============================================================================

class caliptra_ss_usb_fs_dev1_bulk_loopback_sequence extends caliptra_ss_usb_base_sequence;

    `uvm_object_utils(caliptra_ss_usb_fs_dev1_bulk_loopback_sequence)

    function new(string name = "caliptra_ss_usb_fs_dev1_bulk_loopback_sequence");
        super.new(name);
    endfunction

    virtual task body();
        svt_usb_agent         host_agent_h;
        svt_usb_configuration usb_cfg;
        svt_usb_status        shared_status;
        svt_usb_transfer      bulk_out_req;
        svt_usb_transfer      bulk_in_req;
        bit [7:0]             send_data[];
        int unsigned          i;

        host_agent_h  = resolve_host_agent();
        shared_status = resolve_shared_status();
        usb_cfg       = resolve_usb_cfg();

        // Step 1: Wait for FS link ENABLED.
        wait_for_link_enabled(shared_status, "FS host link");

        // Step 2 (not needed): No explicit SE0 bus reset via se0_seq.
        // drive_reset_time is set in the test cfg so the VIP autonomously drives
        // SE0 for 150 us BEFORE transitioning to ENABLED (same as HS mode which
        // drives SE0+chirp mandatorily per USB 2.0 spec). By the time this
        // sequence sees ENABLED the DUT has already received its bus reset.

        // Step 3: Start SOF generation to keep the FS link alive.
        start_sof_generation();

        // Step 4: Post-reset settling delay.
        // Allow MCU firmware time to handle DRES_C interrupt, call
        // usb_handle_bus_reset() / usb_ep0_reinit(), and re-arm EP0 buffers
        // before the first SETUP token arrives on the bus.
        #50us;

        // Step 5: Enumerate the hub at address 1, bring up hub downstream
        // port 2, then enumerate USBDC1 at address 2 (base-class A -> B -> C).
        enumerate_hub_and_usbdc1(host_agent_h, usb_cfg);

        `uvm_info("USB_FS_LOOPBACK_SEQ", "FS enumeration complete.", UVM_LOW)
        #10us;


        // Step 6: Send 64 bytes of bulk OUT data to EP1.
        // Data pattern: byte[i] = i (0x00, 0x01, ... 0x3F).
        send_data = new[64];
        for (i = 0; i < 64; i++) send_data[i] = i[7:0];

        // Bulk OUT via the base-class helper: it forks the NOTIFY wait before
        // finish_item, which a single 64-byte FS bulk packet needs (the event
        // can fire before a sequential wait would arm). See do_data_xfer() in
        // caliptra_ss_usb_base_sequence.svh.
        do_data_xfer(
            .agent_h            (host_agent_h),
            .usb_cfg            (usb_cfg),
            .xfer_kind          (svt_usb_transfer::BULK_OUT_TRANSFER),
            .device_addr        (2),
            .ep_num             (1),
            .byte_count         (64),
            .ep_anchor_idx      (2),
            .label              ("FS_BULK_OUT_EP1"),
            .req                (bulk_out_req),
            .obj_name           ("bulk_out_req"),
            .payload_data       (send_data),
            .no_zero_length_end (1));

        // Allow MCU firmware time to copy EP1 OUT data to EP1 IN buffer and arm IN.
        #20us;

        // Step 7: Read 64 bytes back from EP1 IN (loopback).
        do_data_xfer(
            .agent_h       (host_agent_h),
            .usb_cfg       (usb_cfg),
            .xfer_kind     (svt_usb_transfer::BULK_IN_TRANSFER),
            .device_addr   (2),
            .ep_num        (1),
            .byte_count    (64),
            .ep_anchor_idx (1),
            .label         ("FS_BULK_IN_EP1"),
            .req           (bulk_in_req),
            .obj_name      ("bulk_in_req"));

        // Step 8: Verify loopback data content.
        begin
            int mismatch_count;
            mismatch_count = 0;
            for (int unsigned bi = 0; bi < 64; bi++) begin
                if (bulk_in_req.payload.data[bi] !== send_data[bi]) begin
                    `uvm_error("USB_FS_LOOPBACK_SEQ",
                        $sformatf("Loopback mismatch at byte[%0d]: sent=0x%02h received=0x%02h",
                                  bi, send_data[bi], bulk_in_req.payload.data[bi]))
                    mismatch_count++;
                end
            end
            if (mismatch_count == 0)
                `uvm_info("USB_FS_LOOPBACK_SEQ",
                    "Loopback data check PASSED: all 64 bytes match.", UVM_LOW)
            else
                `uvm_error("USB_FS_LOOPBACK_SEQ",
                    $sformatf("Loopback data check FAILED: %0d byte(s) mismatched.",
                              mismatch_count))
        end

        // Allow MCU firmware time to complete and log result.
        #20us;

        `uvm_info("USB_FS_LOOPBACK_SEQ",
            "USB FS device bulk loopback sequence complete.", UVM_LOW)
    endtask

endclass

`endif // CALIPTRA_SS_USB_FS_DEV1_BULK_LOOPBACK_SEQUENCE_SV
