// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// -----------------------------------------------------------------------------
// USBDC1 (device1) variant, generated by tools/scripts/gen_usb_dev_variants.py
// from the USBDC0 source family. Differences from the source:
//   - hub-class port requests target downstream port 2 (USBDC1) instead of
//     port 1 (USBDC0);
//   - the matching firmware is built with -DUSB_DEV_SEL=1 so the shared USB
//     library addresses the USBDC1 register/DMA aperture at 0x2001_0000 /
//     0x2001_0100.
// The bus-level protocol, endpoint configuration and assigned USB device
// address (2) are unchanged - USBDC1 is functionally identical to USBDC0.
// -----------------------------------------------------------------------------
`ifndef CALIPTRA_SS_USB_DEV1_INIT_SEQUENCE_SV
`define CALIPTRA_SS_USB_DEV1_INIT_SEQUENCE_SV

// =============================================================================
// USB init sequence for the hub-composite topology (single host_agent, UTMI+).
//
// The environment creates one host_agent. host_cfg is the local host stack and
// remote_cfg is the modeled device PHY connected to the DUT over one svt_usb_if.
// Auto-attach and reset/chirp handling are driven by the VIP link state machine;
// this sequence waits for HS link-up before issuing protocol transfers.
//
// The DUT is a USB hub-composite IP: an on-chip 2-port hub with an embedded
// downstream device controller (USBDC1, the MCU-owned DUT device). USBDC1
// sits BEHIND the hub, not directly on the bus. Firmware brings the hub up
// (HUB RAM programming, HUB_EN, then HUB_CONNECT); the host must enumerate
// the hub itself before it can ever see USBDC1, then must explicitly reset/
// enable the hub's downstream port before the hub forwards any SETUP
// traffic to USBDC1.
//
// Sequence flow (see claude_md/09_usb_hub_composite_migration.md Section E):
//   1. Wait for host_agent.shared_status.link_usb_20_state == ENABLED.
//   2. Start SOF generation; allow the DUT firmware a short post-reset
//      settling interval.
//   3. Step 4a - enumerate the HUB itself at address 1 (device + config +
//      hub-class descriptors, SET_CONFIGURATION).
//   4. Step 4b - bring up hub downstream port 2 (where USBDC1 is attached)
//      via hub-class GetPortStatus / ClearFeature(C_PORT_CONNECTION) /
//      SetFeature(PORT_RESET) / ClearFeature(C_PORT_RESET), then reset the
//      VIP's remote device_address anchor back to 0 (USBDC1 answers at
//      address 0 immediately after its port reset, like any freshly-reset
//      device).
//   5. Step 4c - enumerate USBDC1 (behind hub port 2) at address 2:
//      GET_DESCRIPTOR/GET_STATUS/SET_ADDRESS/GET_CONFIGURATION/
//      SET_CONFIGURATION/GET_CONFIGURATION (verify).
//
// This sequence is deliberately minimal (control-plane / enumeration only -
// no data-endpoint traffic, no suspend, no disconnect): it is the smallest,
// fastest smoke test proving boot + EP0 bring-up + enumeration through the
// hub, and the reference device event loop the other USB device tests were
// derived from. Do not grow it into another bulk/data test.
// =============================================================================


// -----------------------------------------------------------------------------
// Note: the optional USB 2.0 port-reset helper class
// caliptra_ss_usb_port_reset_sequence is declared in the dev0 source file
// caliptra_ss_usb_init_sequence.svh and is shared package-wide, so it is not
// re-declared here.
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Top-level init sequence (started on env.host_agent.virt_sequencer).
// -----------------------------------------------------------------------------
class caliptra_ss_usb_dev1_init_sequence extends caliptra_ss_usb_base_sequence;

    `uvm_object_utils(caliptra_ss_usb_dev1_init_sequence)

    function new(string name = "caliptra_ss_usb_dev1_init_sequence");
        super.new(name);
    endfunction

    // -------------------------------------------------------------------------
    // Main body
    // -------------------------------------------------------------------------
    virtual task body();
        svt_usb_agent         host_agent_h;
        svt_usb_configuration usb_cfg;
        svt_usb_status        shared_status;

        // Auto-attach is configured through remote_cfg. Once the modeled device
        // PHY attaches, the host link state machine performs reset, detects the
        // HS chirp from the DUT, and transitions to ENABLED. Transfers must not
        // be issued before ENABLED because the VIP protocol layer has not yet
        // established negotiated speed and endpoint context.
        `uvm_info("USB_DEV1_INIT",
            "Auto-attach in flight via remote_cfg. Waiting for host link to reach ENABLED.",
            UVM_LOW)

        // Resolve the VIP handles needed for the link wait and the transfers.
        host_agent_h  = resolve_host_agent();
        shared_status = resolve_shared_status();
        usb_cfg       = resolve_usb_cfg();

        // Step 1: Wait for the host link to reach ENABLED (untimed).
        wait_for_link_enabled(shared_status, "host link");

        // Step 2: Start SOF generation so the link is not suspended while the
        // enumeration control transfers are issued.
        start_sof_generation();

        // Step 3: Small settling delay before the first SETUP transfer so the
        // DUT firmware has had time to handle the bus-reset interrupt (DRES_C)
        // and re-prime EP0.
        #20us;

        // Step 4: Enumerate the hub at address 1 (step A), bring up hub
        // downstream port 2 where USBDC1 is attached (step B), then enumerate
        // USBDC1 at address 2 including the configuration read-back (step C).
        // All three steps live in caliptra_ss_usb_base_sequence.
        enumerate_hub_and_usbdc1(host_agent_h, usb_cfg);

        `uvm_info("USB_DEV1_INIT", "USB init sequence complete (hub + USBDC1 enumerated).", UVM_LOW)
    endtask



endclass

`endif // CALIPTRA_SS_USB_DEV1_INIT_SEQUENCE_SV
