---
provides: [css_mcu0_veer_el2_defines_pkg]
schema_version: 2.4.0
# requires: [soc_ifc_pkg]
targets:
  rtl:
    directories: 
      - $COMPILE_ROOT/rtl/design
      - $COMPILE_ROOT/rtl/defines
      - $COMPILE_ROOT/rtl/design/include
    files:
      - $COMPILE_ROOT/rtl/defines/css_mcu0_el2_pdef.vh
      - $COMPILE_ROOT/rtl/design/include/el2_def.sv
      - $COMPILE_ROOT/rtl/defines/css_mcu0_common_defines.vh
      - $COMPILE_ROOT/rtl/design/lib/beh_lib.sv
  tb:
    directories:
      - $COMPILE_ROOT/rtl/design
      - $COMPILE_ROOT/rtl/defines
      - $COMPILE_ROOT/rtl/design/include 
    files:
      - $COMPILE_ROOT/rtl/defines/css_mcu0_el2_pdef.vh
      - $COMPILE_ROOT/rtl/design/include/el2_def.sv
      - $COMPILE_ROOT/rtl/defines/css_mcu0_common_defines.vh
      - $COMPILE_ROOT/rtl/design/lib/beh_lib.sv
---
provides: [css_mcu0_veer_el2_rtl_pkg]
schema_version: 2.4.0
requires: [css_mcu0_veer_el2_defines_pkg]
targets:
  rtl:
    directories:
      - $COMPILE_ROOT/rtl/design
      - $COMPILE_ROOT/rtl/defines
      - $COMPILE_ROOT/rtl/design/include
    files:
      - $COMPILE_ROOT/rtl/design/el2_mem.sv
      - $COMPILE_ROOT/rtl/design/el2_dma_ctrl.sv
      - $COMPILE_ROOT/rtl/design/el2_pmp.sv
      - $COMPILE_ROOT/rtl/design/el2_pic_ctrl.sv
      - $COMPILE_ROOT/rtl/design/el2_veer.sv
      - $COMPILE_ROOT/rtl/design/el2_veer_wrapper.sv
      - $COMPILE_ROOT/rtl/design/dbg/el2_dbg.sv
      - $COMPILE_ROOT/rtl/design/dmi/dmi_mux.v
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_decode_ctl.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_gpr_ctl.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_ib_ctl.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_pmp_ctl.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_tlu_ctl.sv
      - $COMPILE_ROOT/rtl/design/dec/el2_dec_trigger.sv
      - $COMPILE_ROOT/rtl/design/dmi/dmi_jtag_to_core_sync.v
      - $COMPILE_ROOT/rtl/design/dmi/dmi_wrapper.v
      - $COMPILE_ROOT/rtl/design/dmi/rvjtag_tap.v
      - $COMPILE_ROOT/rtl/design/exu/el2_exu_alu_ctl.sv
      - $COMPILE_ROOT/rtl/design/exu/el2_exu_div_ctl.sv
      - $COMPILE_ROOT/rtl/design/exu/el2_exu_mul_ctl.sv
      - $COMPILE_ROOT/rtl/design/exu/el2_exu.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_aln_ctl.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_bp_ctl.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_compress_ctl.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_iccm_mem.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_ic_mem.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_ifc_ctl.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu_mem_ctl.sv
      - $COMPILE_ROOT/rtl/design/ifu/el2_ifu.sv
      - $COMPILE_ROOT/rtl/design/lib/ahb_to_axi4.sv
      - $COMPILE_ROOT/rtl/design/lib/axi4_to_ahb.sv
      - $COMPILE_ROOT/rtl/design/lib/el2_lib.sv
      - $COMPILE_ROOT/rtl/design/lib/mem_lib.sv
      - $COMPILE_ROOT/rtl/design/lib/el2_mem_if.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_addrcheck.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_bus_buffer.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_bus_intf.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_clkdomain.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_dccm_ctl.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_dccm_mem.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_ecc.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_lsc_ctl.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_stbuf.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu.sv
      - $COMPILE_ROOT/rtl/design/lsu/el2_lsu_trigger.sv
    tops: [el2_veer_wrapper]
  rtl_lint:
    directories: []
    waiver_files:
      - $MSFT_REPO_ROOT/src/riscv_core/veer_el2/config/rev1p0_lint/mcu_el2_veer_wrapper/sglint_waivers
global:
  tool:
    vcs:
      default:
        - +define+css_mcu0_RV_BUILD_AXI4
        - '-assert svaext'
        #- '-v2k_generate'
#---
#provides: [el2_veer_wrapper_tb]  
#schema_version: 2.4.0
#requires: 
#  - caliptra_top_defines
#  - el2_veer_pkg
#  - el2_veer_wrapper
#targets:
#  tb:
#    directories: 
#      - $COMPILE_ROOT/tb
#    files:
#      - $COMPILE_ROOT/rtl/ifu/mcu_el2_ifu_tb_memread.sv
#      - $COMPILE_ROOT/tb/mcu_el2_veer_wrapper_tb.sv
#      - $COMPILE_ROOT/tb/ahb_sif.sv
#    tops: [el2_veer_wrapper_tb]
#  sim:
#    pre_exec: $MSFT_TOOLS/scripts/run_test_makefile
#global:
#  tool:
#    vcs:
#      default:
#        - '-assert svaext'
#        #- '-v2k_generate'
#        #- '-timescale=1ns/1ps'
#        - '-noinherit_timescale=1ns/1ps'
#        #- '-ucli -i dump.ucli'
#      #sim:
#        #- '-ucli -i dump.ucli'
