// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Description: USB FS device disconnect/reconnect test firmware for Caliptra SS.
//
// This is the full-speed variant of caliptra_ss_usb_hs_dev_disconnect.c. The
// only functional difference is the USB bring-up call: this test uses
// boot_usb_core_fs() instead of boot_usb_core(). boot_usb_core_fs() is
// identical to boot_usb_core() except that it sets DEVCMDSTAT.PFSC (bit 21,
// USBHSD_DEVCMDSTAT_PFSC_MASK) to suppress the device-side K-chirp so the link
// negotiates and stays at full-speed for the FS-only host VIP
// (high_speed_capable=0). Every other phase (hub connect, FORCE_VBUS clear,
// enumeration, disconnect detect via DCON_C / VBUS_DEBOUNCED, reconnect and
// re-enumeration) is speed-agnostic and unchanged.
//
// Test flow:
//   1. Boot MCU and USB device controller in FS-only mode (boot_usb_core_fs).
//      Clear FORCE_VBUS so the controller monitors the real VBus pin (required
//      for disconnect detection via DCON_C / VBUS_DEBOUNCED).
//   2. Enumerate: service EP0 SETUP tokens (GET_DESCRIPTOR, SET_ADDRESS,
//      SET_CONFIGURATION) inline in the poll loop. Bus resets are handled
//      via usb_handle_bus_reset() on every DEV_INT.
//   3. Wait for USB_SOF_COUNT FRAME_INT (SOF) events while continuing to
//      service EP0.
//   4. Detect VBus removal: poll for DCON_C set and VBUS_DEBOUNCED clear.
//      On detection clear DCON (drops FsPullup) then clear DCON_C (W1C).
//      Verify VBUS_DEBOUNCED is clear.
//   5. Re-enumerate after reconnect (same as phase 2).
//   6. Wait for USB_SOF_COUNT more FRAME_INT events.
//   7. Report PASSED.


// -----------------------------------------------------------------------------
// USBDC1 (device1) variant, generated by tools/scripts/gen_usb_dev_variants.py
// from the USBDC0 source test. The firmware source is unchanged apart from
// names: the shared USB library is retargeted to the USBDC1 aperture purely by
// -DUSB_DEV_SEL=1, which the yml passes through BUILD_CFLAGS. See the
// USB_DEV_SEL block in src/integration/test_suites/libs/usb/usb.h.
// -----------------------------------------------------------------------------
#include "soc_address_map.h"
#include "printf.h"
#include "riscv_hw_if.h"
#include "soc_ifc.h"
#include "caliptra_ss_lib.h"
#include "usb.h"
#include "stdint.h"
#include "veer-csr.h"

// Poll timeout: number of main-loop iterations before declaring a timeout.
// Each iteration is ~51 ns at MCU clock rate. This is a failure ceiling, not a
// dwell: every loop that uses it exits early via break or its loop condition as
// soon as the awaited event arrives.
//
// FS TIMING NOTE: this ceiling must clear the full-speed VBus debounce. The
// device controller de-asserts VBUS_DEBOUNCED (which arms the Phase 3
// DCON_C + !VBUS_DEBOUNCED detect) only after its DebounceTimer counts
// VBUS_DEBOUNCE_TIME (=3) edges of the frame-driven pie_isotoggle. In FS that
// toggle runs at the 1 ms SOF rate (8x slower than the 125 us HS microframe),
// so the debounce alone takes 3-4 ms of wall time after VBus is removed, versus
// ~375 us in HS. 200000 iterations is ~10 ms, roughly 2x the worst-case FS
// disconnect-detect latency so the poll cannot expire before the debounce.
#define USB_POLL_TIMEOUT    200000

// Number of SOF (FRAME_INT) events to count on each side of the disconnect.
#define USB_SOF_COUNT       6

// Number of standard enumeration control transfers expected:
// GET_DESCRIPTOR + SET_ADDRESS + SET_CONFIGURATION = 3.
#define USB_ENUM_XFER_COUNT 3

// Post-re-enumeration EP0 service window. After Phase 4 has counted
// USB_ENUM_XFER_COUNT transfers the UVM sequence is not finished: it still
// drives GET_DESCRIPTOR at the new address and SET_CONFIGURATION to USBDC1. If
// firmware halts immediately, EP0 is never re-armed for those remaining SETUP
// packets and the device NAKs a SETUP token, which the VIP flags as a protocol
// violation. This is a backstop ceiling; the loop normally exits via the
// quiet-period check below.
#define USB_POST_ENUM_SERVICE_ITERS 40000

// Number of additional control transfers the host drives after the counted
// re-enumeration transfers (GET_DESCRIPTOR at new address + SET_CONFIGURATION).
#define USB_POST_ENUM_XFER_COUNT 2

// Quiet period, in poll iterations, that must elapse with no EP0 SETUP activity
// before Phase 4b is allowed to finish. Requiring an idle stretch means the
// window only closes once the host has actually gone quiet, so there is no
// SETUP left outstanding when the firmware halts.
#define USB_POST_ENUM_QUIET_ITERS 2000


volatile char* stdout = (char *)SOC_MCI_TOP_MCI_REG_DEBUG_OUT;

#ifdef CPT_VERBOSITY
    enum printf_verbosity verbosity_g = CPT_VERBOSITY;
#else
    enum printf_verbosity verbosity_g = LOW;
#endif

void main(void) {
    uint32_t reg_data;
    uint32_t poll_count;
    uint32_t intstat;
    uint32_t xfer_count;
    // Poll index of the most recent EP0 SETUP, used by the Phase 4b quiet check.
    uint32_t last_setup_poll;
    uint32_t sof_count;

    VPRINTF(LOW, "=================\nMCU: USB FS device disconnect test\n=================\n\n");

    boot_mcu();
    // FS-only bring-up: boot_usb_core_fs() sets DEVCMDSTAT.PFSC (bit 21) to
    // suppress the device K-chirp so the link stays full-speed for the FS-only
    // host VIP. This is the only functional difference from the HS variant.
    boot_usb_core_fs();

    // Connect the compound hub upstream.
    //
    // boot_usb_core_fs() (like boot_usb_core()) calls usb_hub_init_and_connect(),
    // which programs the HUB RAM and sets HUB_EN only - HUB_CONNECT is
    // deliberately deferred so that USBDC1 is fully programmed before the host
    // can see anything on the bus. Complete the second phase here so the hub
    // attaches upstream and the host drives a bus reset.
    usb_hub_connect();

    // Clear FORCE_VBUS so the controller monitors the real VBus pin.
    // boot_usb_core_fs() sets FORCE_VBUS=1 for normal enumeration tests.
    // With FORCE_VBUS=1 the DUT ignores VBus removal; DCON_C never fires
    // and disconnect detection is impossible.
    //
    // Done after usb_hub_connect() so the hub bring-up write to HUB_CTRL
    // cannot race this DEVCMDSTAT read-modify-write.
    {
        uint32_t cmd = lsu_read_32(USB_DEV_DEVCMDSTAT);
        cmd &= ~USBHSD_DEVCMDSTAT_FORCE_VBUS_MASK;
        lsu_write_32(USB_DEV_DEVCMDSTAT, cmd);
        VPRINTF(LOW, "MCU: FORCE_VBUS cleared (DEVCMDSTAT=0x%x)\n", cmd);
    }

    mcu_cptra_advance_brkpoint();
    mcu_cptra_user_init();
    mcu_cptra_poll_mb_ready();
    VPRINTF(LOW, "MCU: Caliptra core ready\n");

    // ------------------------------------------------------------------
    // Phase 1: Enumeration (initial connect).
    // Service EP0 SETUP tokens until USB_ENUM_XFER_COUNT transfers are
    // handled. Bus resets are serviced inline via DEV_INT / usb_handle_bus_reset().
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 1 - initial enumeration\n");
    xfer_count = 0;
    for (poll_count = 0;
         poll_count < USB_POLL_TIMEOUT && xfer_count < USB_ENUM_XFER_COUNT;
         poll_count++) {

        reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
        intstat  = lsu_read_32(USB_DEV_INTSTAT);

        // DEV_INT: bus-level events (bus reset, connect/disconnect change).
        // Read DEVCMDSTAT before the W1C write - the W1C on DEV_INT also
        // clears the change-detect bits (DRES_C, DSUS_C, DCON_C) in
        // DEVCMDSTAT, so reg_data must be sampled first.
        if (intstat & USBHSD_INTSTAT_DEV_INT_MASK) {
            if (reg_data & USBHSD_DEVCMDSTAT_DRES_C_MASK) {
                usb_handle_bus_reset();
            }
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_DEV_INT_MASK);
        }

        // EP0 OUT: SETUP or status-phase OUT token.
        if (intstat & USBHSD_INTSTAT_EP0OUT_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0OUT_MASK);
            if (reg_data & USBHSD_DEVCMDSTAT_SETUP_MASK) {
                if (usb_handle_control_transfer()) {
                    xfer_count++;
                    VPRINTF(LOW, "MCU: enumeration transfer %d of %d\n",
                            xfer_count, USB_ENUM_XFER_COUNT);
                }
            }
        }

        // EP0 IN: clear interrupt.
        if (intstat & USBHSD_INTSTAT_EP0IN_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0IN_MASK);
        }
    }

    if (xfer_count < USB_ENUM_XFER_COUNT) {
        VPRINTF(LOW, "MCU: FAIL - enumeration timeout (got %d of %d)\n",
                xfer_count, USB_ENUM_XFER_COUNT);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: Enumeration complete (%d transfers).\n", xfer_count);

    // ------------------------------------------------------------------
    // Phase 2: FRAME_INT enable/disable. The SOF-counting loop is retained
    // as commented-out reference (matches the HS variant); no SOF events are
    // counted in the current build.
    // ------------------------------------------------------------------

    // Clear any pending FRAME_INT before enabling.
    lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_FRAME_INT_MASK);

    // Enable FRAME_INT in INTEN.
    lsu_write_32(USB_DEV_INTEN,
                 lsu_read_32(USB_DEV_INTEN) | USBHSD_INTEN_FRAME_INT_EN_MASK);

    // Disable FRAME_INT.
    lsu_write_32(USB_DEV_INTEN,
                 lsu_read_32(USB_DEV_INTEN) & ~USBHSD_INTEN_FRAME_INT_EN_MASK);

    // ------------------------------------------------------------------
    // Phase 3: Disconnect detection.
    // Poll for DCON_C set and VBUS_DEBOUNCED clear. Service EP0 and
    // DEV_INT inline on every iteration.
    // On detection: clear DCON (de-asserts FsPullup/TermSelect so the
    // VIP link state machine can leave ENABLED state), then clear DCON_C (W1C).
    //
    // NOTE: DCON is R/W firmware-controlled. Hardware does not clear DCON
    // on VBus removal. "DCON_C && !DCON" is therefore never true. Detect
    // "DCON_C && !VBUS_DEBOUNCED" instead - hardware clears VBUS_DEBOUNCED
    // when VBus is removed - then explicitly clear DCON to drop FsPullup.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 3 - waiting for disconnect (DCON_C + VBUS_DEBOUNCED=0)\n");
    for (poll_count = 0; poll_count < USB_POLL_TIMEOUT; poll_count++) {
        reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
        intstat  = lsu_read_32(USB_DEV_INTSTAT);

        // Service EP0 on every pass (VIP may send SETUP packets while waiting).
        if (intstat & USBHSD_INTSTAT_EP0OUT_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0OUT_MASK);
            if (reg_data & USBHSD_DEVCMDSTAT_SETUP_MASK) {
                usb_handle_control_transfer();
            }
        }

        if (intstat & USBHSD_INTSTAT_EP0IN_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0IN_MASK);
        }

        // DCON_C is a change-detect bit sampled before any W1C write above,
        // so its value in reg_data is still valid for the check below.
        if ((reg_data & USBHSD_DEVCMDSTAT_DCON_C_MASK) &&
            !(reg_data & USBHSD_DEVCMDSTAT_VBUS_DEBOUNCED_MASK)) {
            VPRINTF(LOW, "MCU: Disconnect detected - DEVCMDSTAT=0x%x\n", reg_data);

            // Clear DCON so FsPullup/TermSelect de-asserts.
            // VIP link state machine requires FsPullup low to leave ENABLED.
            {
                uint32_t cmd = lsu_read_32(USB_DEV_DEVCMDSTAT);
                cmd &= ~USBHSD_DEVCMDSTAT_DCON_MASK;
                lsu_write_32(USB_DEV_DEVCMDSTAT, cmd);
                VPRINTF(LOW, "MCU: DCON cleared (DEVCMDSTAT=0x%x)\n", cmd);
            }

            // Clear DCON_C (W1C) after DCON is de-asserted.
            // Use RMW so DEV_EN and all other sticky bits are preserved.
            {
                uint32_t cmd = lsu_read_32(USB_DEV_DEVCMDSTAT);
                cmd |= USBHSD_DEVCMDSTAT_DCON_C_MASK;
                lsu_write_32(USB_DEV_DEVCMDSTAT, cmd);
            }
            break;
        }
    }

    if (poll_count >= USB_POLL_TIMEOUT) {
        VPRINTF(LOW, "MCU: FAIL - timeout waiting for disconnect\n");
        csr_write_mpmc_halt();
    }

    // Verify VBUS_DEBOUNCED is clear after disconnect.
    reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
    if (reg_data & USBHSD_DEVCMDSTAT_VBUS_DEBOUNCED_MASK) {
        VPRINTF(LOW, "MCU: FAIL - VBUS_DEBOUNCED still set after disconnect (DEVCMDSTAT=0x%x)\n",
                reg_data);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: USB bus disconnected. VBUS_DEBOUNCED clear.\n");

    // ------------------------------------------------------------------
    // Phase 3b: Wait for VBus to return (VBUS_DEBOUNCED set), then
    // re-assert DCON to bring FsPullup back high.
    //
    // After DCON was cleared in Phase 3, the device FsPullup is low.
    // The VIP host cannot see the device as re-attached until FsPullup
    // goes high again. Without re-asserting DCON here, the VIP link
    // state machine never leaves DISCONNECTED and never drives a bus
    // reset, so the FS re-attach / ENABLED state is never reached.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 3b - waiting for VBus to return (VBUS_DEBOUNCED)\n");
    for (poll_count = 0; poll_count < USB_POLL_TIMEOUT; poll_count++) {
        reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
        if (reg_data & USBHSD_DEVCMDSTAT_VBUS_DEBOUNCED_MASK) {
            VPRINTF(LOW, "MCU: VBus returned - DEVCMDSTAT=0x%x\n", reg_data);
            break;
        }
    }
    if (poll_count >= USB_POLL_TIMEOUT) {
        VPRINTF(LOW, "MCU: FAIL - timeout waiting for VBus to return\n");
        csr_write_mpmc_halt();
    }

    // Re-assert DCON so FsPullup goes high and VIP host can detect the
    // device re-attached. This lets the host drive a fresh bus reset and
    // eventually brings the link back to ENABLED.
    {
        uint32_t cmd = lsu_read_32(USB_DEV_DEVCMDSTAT);
        cmd |= USBHSD_DEVCMDSTAT_DCON_MASK;
        lsu_write_32(USB_DEV_DEVCMDSTAT, cmd);
        VPRINTF(LOW, "MCU: DCON re-asserted (DEVCMDSTAT=0x%x)\n", cmd);
    }

    // ------------------------------------------------------------------
    // Phase 4: Re-enumeration after reconnect.
    // Same inline pattern as Phase 1. The VIP reconnects VBus and drives
    // a new bus reset; DEV_INT/DRES_C is handled inline.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 4 - waiting for host to reconnect and re-enumerate\n");
    xfer_count = 0;
    for (poll_count = 0;
         poll_count < USB_POLL_TIMEOUT && xfer_count < USB_ENUM_XFER_COUNT;
         poll_count++) {

        reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
        intstat  = lsu_read_32(USB_DEV_INTSTAT);

        if (intstat & USBHSD_INTSTAT_DEV_INT_MASK) {
            if (reg_data & USBHSD_DEVCMDSTAT_DRES_C_MASK) {
                usb_handle_bus_reset();
            }
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_DEV_INT_MASK);
        }

        if (intstat & USBHSD_INTSTAT_EP0OUT_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0OUT_MASK);
            if (reg_data & USBHSD_DEVCMDSTAT_SETUP_MASK) {
                if (usb_handle_control_transfer()) {
                    xfer_count++;
                    VPRINTF(LOW, "MCU: re-enumeration transfer %d of %d\n",
                            xfer_count, USB_ENUM_XFER_COUNT);
                }
            }
        }

        if (intstat & USBHSD_INTSTAT_EP0IN_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0IN_MASK);
        }
    }

    if (xfer_count < USB_ENUM_XFER_COUNT) {
        VPRINTF(LOW, "MCU: FAIL - re-enumeration timeout (got %d of %d)\n",
                xfer_count, USB_ENUM_XFER_COUNT);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: Re-enumeration complete (%d transfers).\n", xfer_count);

    // ------------------------------------------------------------------
    // Phase 4b: Post-re-enumeration EP0 service window.
    //
    // The host-side UVM sequence continues past the counted transfers: after
    // SET_ADDRESS it re-anchors the VIP to the new address and drives
    // GET_DESCRIPTOR and SET_CONFIGURATION to USBDC1. Those SETUP packets must
    // still be answered. Halting here leaves EP0 un-armed and the device NAKs a
    // SETUP, which the VIP protocol checker reports as an illegal device
    // response. Keep the same EP0 / DEV_INT service pattern running for a
    // bounded window that closes only once the host has gone quiet.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 4b - servicing EP0 for the tail of host enumeration\n");
    xfer_count = 0;
    last_setup_poll = 0;
    for (poll_count = 0; poll_count < USB_POST_ENUM_SERVICE_ITERS; poll_count++) {

        // Exit only when the host has both driven the transfers we expect and
        // then stayed quiet long enough that nothing is still in flight.
        if (xfer_count >= USB_POST_ENUM_XFER_COUNT &&
            (poll_count - last_setup_poll) > USB_POST_ENUM_QUIET_ITERS) {
            break;
        }

        reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
        intstat  = lsu_read_32(USB_DEV_INTSTAT);

        if (intstat & USBHSD_INTSTAT_DEV_INT_MASK) {
            if (reg_data & USBHSD_DEVCMDSTAT_DRES_C_MASK) {
                usb_handle_bus_reset();
            }
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_DEV_INT_MASK);
        }

        if (intstat & USBHSD_INTSTAT_EP0OUT_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0OUT_MASK);
            if (reg_data & USBHSD_DEVCMDSTAT_SETUP_MASK) {
                // Any SETUP, counted or not, restarts the quiet timer.
                last_setup_poll = poll_count;
                if (usb_handle_control_transfer()) {
                    xfer_count++;
                    VPRINTF(LOW, "MCU: post-enumeration transfer %d of %d\n",
                            xfer_count, USB_POST_ENUM_XFER_COUNT);
                }
            }
        }

        if (intstat & USBHSD_INTSTAT_EP0IN_MASK) {
            lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_EP0IN_MASK);
        }
    }

    if (xfer_count < USB_POST_ENUM_XFER_COUNT) {
        // Not fatal on its own: the host may legitimately drive fewer
        // trailing transfers. Report it so a NAK-on-SETUP protocol error
        // from the VIP can be correlated with a short service window.
        VPRINTF(LOW, "MCU: WARNING - post-enumeration service window ended with %d of %d transfers\n",
                xfer_count, USB_POST_ENUM_XFER_COUNT);
    } else {
        VPRINTF(LOW, "MCU: Post-enumeration service complete (%d transfers).\n",
                xfer_count);
    }

    // ------------------------------------------------------------------
    // Phase 5: FRAME_INT enable (SOF-counting loop retained as reference,
    // matching the HS variant).
    // ------------------------------------------------------------------
    lsu_write_32(USB_DEV_INTSTAT, USBHSD_INTSTAT_FRAME_INT_MASK);
    lsu_write_32(USB_DEV_INTEN,
                 lsu_read_32(USB_DEV_INTEN) | USBHSD_INTEN_FRAME_INT_EN_MASK);

    // ------------------------------------------------------------------
    // All phases passed.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: USB FS disconnect test PASSED\n");
    reg_data = lsu_read_32(USB_DEV_DEVCMDSTAT);
    VPRINTF(LOW, "MCU: USB DEVCMDSTAT final = 0x%x\n", reg_data);
    csr_write_mpmc_halt();
}

// File contains AI-generated response based on internal company sources
