---
provides: [uvmf_fuse_ctrl]
schema_version: 2.4.0
requires:
  - uvmf_lib
  - fuse_ctrl
targets:
  tb:
    directories:  
      - ${COMPILE_ROOT}/../rtl
      - ${COMPILE_ROOT}/../../libs/rtl
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/fuse_ctrl_env_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/fuse_ctrl_env_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/parameters
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/sequences
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/tests
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/testbench
    files:
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/fuse_ctrl_rst_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/fuse_ctrl_rst_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/src/fuse_ctrl_rst_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/src/fuse_ctrl_rst_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_in_pkg/src/fuse_ctrl_rst_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/fuse_ctrl_rst_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/fuse_ctrl_rst_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/src/fuse_ctrl_rst_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/src/fuse_ctrl_rst_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_rst_out_pkg/src/fuse_ctrl_rst_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/fuse_ctrl_core_axi_read_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/fuse_ctrl_core_axi_read_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/src/fuse_ctrl_core_axi_read_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/src/fuse_ctrl_core_axi_read_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_in_pkg/src/fuse_ctrl_core_axi_read_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/fuse_ctrl_core_axi_read_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/fuse_ctrl_core_axi_read_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/src/fuse_ctrl_core_axi_read_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/src/fuse_ctrl_core_axi_read_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_read_out_pkg/src/fuse_ctrl_core_axi_read_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/fuse_ctrl_core_axi_write_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/fuse_ctrl_core_axi_write_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/src/fuse_ctrl_core_axi_write_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/src/fuse_ctrl_core_axi_write_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_in_pkg/src/fuse_ctrl_core_axi_write_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/fuse_ctrl_core_axi_write_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/fuse_ctrl_core_axi_write_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/src/fuse_ctrl_core_axi_write_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/src/fuse_ctrl_core_axi_write_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_core_axi_write_out_pkg/src/fuse_ctrl_core_axi_write_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/fuse_ctrl_prim_axi_read_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/fuse_ctrl_prim_axi_read_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/src/fuse_ctrl_prim_axi_read_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/src/fuse_ctrl_prim_axi_read_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_in_pkg/src/fuse_ctrl_prim_axi_read_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/fuse_ctrl_prim_axi_read_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/fuse_ctrl_prim_axi_read_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/src/fuse_ctrl_prim_axi_read_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/src/fuse_ctrl_prim_axi_read_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_read_out_pkg/src/fuse_ctrl_prim_axi_read_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/fuse_ctrl_prim_axi_write_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/fuse_ctrl_prim_axi_write_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/src/fuse_ctrl_prim_axi_write_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/src/fuse_ctrl_prim_axi_write_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_in_pkg/src/fuse_ctrl_prim_axi_write_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/fuse_ctrl_prim_axi_write_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/fuse_ctrl_prim_axi_write_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/src/fuse_ctrl_prim_axi_write_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/src/fuse_ctrl_prim_axi_write_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_prim_axi_write_out_pkg/src/fuse_ctrl_prim_axi_write_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/fuse_ctrl_secreg_axi_read_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/fuse_ctrl_secreg_axi_read_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/src/fuse_ctrl_secreg_axi_read_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/src/fuse_ctrl_secreg_axi_read_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_in_pkg/src/fuse_ctrl_secreg_axi_read_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/fuse_ctrl_secreg_axi_read_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/fuse_ctrl_secreg_axi_read_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/src/fuse_ctrl_secreg_axi_read_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/src/fuse_ctrl_secreg_axi_read_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_secreg_axi_read_out_pkg/src/fuse_ctrl_secreg_axi_read_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/fuse_ctrl_lc_otp_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/fuse_ctrl_lc_otp_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/src/fuse_ctrl_lc_otp_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/src/fuse_ctrl_lc_otp_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_in_pkg/src/fuse_ctrl_lc_otp_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/fuse_ctrl_lc_otp_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/fuse_ctrl_lc_otp_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/src/fuse_ctrl_lc_otp_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/src/fuse_ctrl_lc_otp_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_lc_otp_out_pkg/src/fuse_ctrl_lc_otp_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/fuse_ctrl_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/fuse_ctrl_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/src/fuse_ctrl_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/src/fuse_ctrl_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_in_pkg/src/fuse_ctrl_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/fuse_ctrl_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/fuse_ctrl_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/src/fuse_ctrl_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/src/fuse_ctrl_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/fuse_ctrl_out_pkg/src/fuse_ctrl_out_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/fuse_ctrl_env_pkg/fuse_ctrl_env_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/parameters/fuse_ctrl_parameters_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/sequences/fuse_ctrl_sequences_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/tests/fuse_ctrl_tests_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/testbench/hdl_top.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/fuse_ctrl/tb/testbench/hvl_top.sv
    tops:
      - hdl_top
      - hvl_top
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - '-noinherit_timescale=1ns/1ps'
        #sim:
        #- '-ucli -i dump.ucli'
        # Suppress a warning due to calling $fgets as task instead of function
        # i.e. discarding the return value. This is in auto-generated code.
        - '+warn=noRVOSFD'
        # Suppress NOTE about repeated package imports within the same
        # package (each .svh file included in the auto-generated UVM _pkg.sv
        # files imports the same dependencies)
        - '-suppress=SV-LCM-PPWI'
      elab:
        # Suppress warnings about too few port connections - auto-generated interfaces
        # declare all signals as inout, but are driven at a lower layer than the
        # instantiation, so they will always flag this
        - '-suppress=TFIPC'



