// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description: USB HS device power-down test firmware (Hub-Enabled mode).
//
// In hub-enabled mode the device under test (USBDC0) is an embedded
// downstream device of the compound hub. A GENUINE power-down of USBDC0 is
// driven by the sequence as a hub-class ClearFeature(PORT_ENABLE) on the
// downstream port where USBDC0 is attached (port 1). Per the hub RTL
// (usb_app_hw_hub.m.vhdl PROC_REQUEST_HANDLING) this forces
//   hub_port_enable_int(0) <= '0'
// and per the compound structure netlist USBDC0's controller enable is gated
// by that signal:
//   usbreg_deviceenabled(1) <= hub_port_enable(0) and usbreg_arm_deviceenabled
// so USBDC0's device controller is degated (deviceenabled=0) - a real,
// waveform-visible power-down (NOT merely a status-bit toggle). PORT_POWER
// and PORT_SUSPEND are no-ops in this IP and would be a false pass.
//
// From USBDC0's point of view the full power-cycle looks like:
//   1. Initial enumeration behind the hub (host enumerates HUB, brings up
//      the downstream port -> USBDC0 sees a port reset -> USBDC0 is
//      enumerated at address 2).
//   2. Host issues ClearFeature(PORT_ENABLE) on port 1: USBDC0's controller
//      is degated (deviceenabled=0). No USBDC0 interrupt is generated by the
//      degate itself - the port-enable clear happens entirely on the hub
//      side - so USBDC0 simply goes quiet on the bus during this window.
//   3. Host issues SetFeature(PORT_RESET) on port 1: this re-asserts
//      hub_port_enable(0) AND pulses hub_port_reset(0), which drives
//      arm_dev_portreset into USBDC0. USBDC0 therefore observes a fresh bus
//      reset (DRES_C set) and returns to the Default state.
//   4. Host re-enumerates USBDC0 at address 2.
//
// USBDC0 stays VBUS-powered throughout (FORCE_VBUS=1 kept set, as programmed
// by boot_usb_core()); the power-down is the controller-enable degate, and
// recovery is proven by the recovery bus reset (DRES_C) that USBDC0 sees when
// PORT_RESET re-enables the port. The firmware must faithfully service EP0
// control transfers AND bus resets across both enumeration rounds, and Phase
// 2 additionally REQUIRES observing the recovery bus reset (DRES_C) so the
// pass cannot be a bare re-enumeration false pass.
//
// Each host-side hub-aware enumeration delivers exactly USB_ENUM_XFER_COUNT
// (7) EP0 control transfers to USBDC0:
//   GET_DESCRIPTOR(DEVICE) @addr0, GET_STATUS @addr0, SET_ADDRESS(2) @addr0,
//   GET_DESCRIPTOR(DEVICE) @addr2, GET_CONFIGURATION @addr2,
//   SET_CONFIGURATION(1) @addr2, GET_CONFIGURATION(verify) @addr2.
//
// Prints "USB HS device powerdown PASSED" once the recovery bus reset is seen
// and re-enumeration completes.


#include "soc_address_map.h"
#include "printf.h"
#include "riscv_hw_if.h"
#include "soc_ifc.h"
#include "caliptra_ss_lib.h"
#include "usb.h"
#include "stdint.h"
#include "veer-csr.h"

// Poll timeout: number of main-loop iterations before declaring a timeout.
// Each iteration is ~51 ns at MCU clock rate; 500000 gives ~25 ms headroom
// which covers enumeration + upstream power-cycle hold + hub re-attach +
// re-enumeration.
#define USB_POLL_TIMEOUT    500000

// Number of EP0 control transfers USBDC0 receives per host-side hub-aware
// enumeration round (see file header for the exact list).
#define USB_ENUM_XFER_COUNT 7

volatile char* stdout = (char *)SOC_MCI_TOP_MCI_REG_DEBUG_OUT;
#ifdef CPT_VERBOSITY
    enum printf_verbosity verbosity_g = CPT_VERBOSITY;
#else
    enum printf_verbosity verbosity_g = LOW;
#endif

// Count of USBDC0 bus resets (DRES_C) observed and serviced since boot.
// A genuine power-down + power-up (ClearFeature(PORT_ENABLE) then
// SetFeature(PORT_RESET)) makes USBDC0 see a fresh bus reset at recovery,
// which increments this counter. Phase 2 requires it to advance so the pass
// cannot be a bare re-enumeration false pass.
static volatile uint32_t usb_bus_reset_count = 0;

// Service one pass of EP0 SETUP handling plus bus-reset handling on USBDC0.
// Returns 1 if a control transfer was handled on this pass, else 0.
static uint32_t usb_service_ep0_once(void) {
    uint32_t reg_data = lsu_read_32(USB_DEV0_DEVCMDSTAT);
    uint32_t intstat  = lsu_read_32(USB_DEV0_INTSTAT);
    uint32_t handled  = 0;

    if (intstat & USBHSD_INTSTAT_DEV_INT_MASK) {
        if (reg_data & USBHSD_DEVCMDSTAT_DRES_C_MASK) {
            usb_handle_bus_reset();
            usb_bus_reset_count++;
        }
        lsu_write_32(USB_DEV0_INTSTAT, USBHSD_INTSTAT_DEV_INT_MASK);
    }

    if (intstat & USBHSD_INTSTAT_EP0OUT_MASK) {
        lsu_write_32(USB_DEV0_INTSTAT, USBHSD_INTSTAT_EP0OUT_MASK);
        if (reg_data & USBHSD_DEVCMDSTAT_SETUP_MASK) {
            if (usb_handle_control_transfer()) {
                handled = 1;
            }
        }
    }

    if (intstat & USBHSD_INTSTAT_EP0IN_MASK) {
        lsu_write_32(USB_DEV0_INTSTAT, USBHSD_INTSTAT_EP0IN_MASK);
    }

    return handled;
}


void main(void) {
    uint32_t reg_data;
    uint32_t poll_count;
    uint32_t xfer_count;

    VPRINTF(LOW, "=================\nMCU: USB HS device powerdown test\n=================\n\n");

    boot_mcu();
    boot_usb_core();
    // Hub-enabled mode: boot_usb_core() calls usb_hub_init_and_connect()
    // internally (programs HUB RAM, sets HUB_EN). USBDC0's own EP list /
    // DEVCMDSTAT / DCON are also fully programmed at this point, so assert
    // HUB_CONNECT here to present the hub upstream. Only after this call
    // does the host see the hub and begin enumerating its downstream port 1
    // (USBDC0), per the reference janus_hub_ctrl_bfm.sv two-phase sequencing.
    usb_hub_connect();

    // NOTE: Do NOT clear FORCE_VBUS here. In hub-enabled mode USBDC0 is an
    // embedded downstream device; the sequence's VBUS_OFF/VBUS_ON acts on
    // the host<->HUB upstream link, which USBDC0 does not observe on its own
    // VBUS_DEBOUNCED bit. Keeping FORCE_VBUS=1 (as programmed by
    // boot_usb_core()) keeps USBDC0 alive across the upstream power-cycle so
    // it re-enumerates cleanly when the hub re-resets its downstream port.

    mcu_cptra_advance_brkpoint();
    mcu_cptra_user_init();
    mcu_cptra_poll_mb_ready();
    VPRINTF(LOW, "MCU: Caliptra core ready\n");

    // ------------------------------------------------------------------
    // Phase 1: Initial enumeration behind the hub.
    // Service EP0 SETUP tokens and bus resets until USB_ENUM_XFER_COUNT
    // control transfers are handled.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "MCU: Phase 1 - initial enumeration\n");
    xfer_count = 0;
    for (poll_count = 0;
         poll_count < USB_POLL_TIMEOUT && xfer_count < USB_ENUM_XFER_COUNT;
         poll_count++) {
        if (usb_service_ep0_once()) {
            xfer_count++;
            VPRINTF(LOW, "MCU: enumeration transfer %d of %d\n",
                    xfer_count, USB_ENUM_XFER_COUNT);
        }
    }

    if (xfer_count < USB_ENUM_XFER_COUNT) {
        VPRINTF(LOW, "MCU: FAIL - enumeration timeout (got %d of %d)\n",
                xfer_count, USB_ENUM_XFER_COUNT);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: Initial enumeration complete (%d transfers).\n", xfer_count);

    // ------------------------------------------------------------------
    // Phase 2: Ride out the genuine power-down, then observe recovery.
    //
    // The sequence powers USBDC0 down with ClearFeature(PORT_ENABLE) on hub
    // port 1: this clears hub_port_enable(0) and degates USBDC0's device
    // controller (deviceenabled=0). That degate is a hub-side event and does
    // NOT raise a USBDC0 interrupt, so USBDC0 simply goes quiet on the bus.
    //
    // Recovery is SetFeature(PORT_RESET) on port 1, which re-asserts
    // hub_port_enable(0) AND pulses hub_port_reset(0). hub_port_reset(0)
    // drives arm_dev_portreset into USBDC0, so USBDC0 observes a fresh bus
    // reset (DRES_C set) and returns to the Default state at address 0. The
    // host then re-enumerates it at address 2.
    //
    // Bus-reset handling here is essential: the recovery port reset must be
    // acknowledged (DRES_C cleared, address shadow reset to 0) or USBDC0 will
    // not respond to the re-enum GET_DESCRIPTOR at address 0. This phase also
    // REQUIRES the DRES_C recovery bus reset to be observed (usb_bus_reset_count
    // must advance) so a bare re-enumeration cannot be scored as a false pass.
    // ------------------------------------------------------------------
    uint32_t bus_reset_count_before_pd = usb_bus_reset_count;
    VPRINTF(LOW, "MCU: Phase 2 - power-down issued; waiting for recovery bus reset"
            " + re-enumeration (reset_count_before=%d)\n", bus_reset_count_before_pd);
    xfer_count = 0;
    for (poll_count = 0;
         poll_count < USB_POLL_TIMEOUT && xfer_count < USB_ENUM_XFER_COUNT;
         poll_count++) {
        if (usb_service_ep0_once()) {
            xfer_count++;
            VPRINTF(LOW, "MCU: re-enumeration transfer %d of %d\n",
                    xfer_count, USB_ENUM_XFER_COUNT);
        }
    }

    if (xfer_count < USB_ENUM_XFER_COUNT) {
        VPRINTF(LOW, "MCU: FAIL - re-enumeration timeout (got %d of %d)\n",
                xfer_count, USB_ENUM_XFER_COUNT);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: Re-enumeration complete (%d transfers).\n", xfer_count);

    // Require the recovery bus reset (DRES_C) to have been observed during
    // Phase 2. Without this the "pass" would only prove a re-enumeration
    // occurred, not that USBDC0 was genuinely power-cycled (degated then
    // reset). SetFeature(PORT_RESET) drives hub_port_reset(0) ->
    // arm_dev_portreset -> DRES_C on USBDC0, so this counter MUST advance.
    if (usb_bus_reset_count <= bus_reset_count_before_pd) {
        VPRINTF(LOW, "MCU: FAIL - no recovery bus reset observed after power-down"
                " (reset_count=%d, before=%d)\n",
                usb_bus_reset_count, bus_reset_count_before_pd);
        csr_write_mpmc_halt();
    }
    VPRINTF(LOW, "MCU: Recovery bus reset observed (reset_count=%d, before=%d).\n",
            usb_bus_reset_count, bus_reset_count_before_pd);

    // ------------------------------------------------------------------
    // All phases passed.
    // ------------------------------------------------------------------
    VPRINTF(LOW, "USB HS device powerdown PASSED\r\n");

    reg_data = lsu_read_32(USB_DEV0_DEVCMDSTAT);
    VPRINTF(LOW, "MCU: USB DEVCMDSTAT final = 0x%x\n", reg_data);
    csr_write_mpmc_halt();
}

// File contains AI-generated response based on internal company sources
