// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Binds OTP_CTRL functional coverage interaface to the top level OTP_CTRL module.
//
// DO NOT EDIT THIS FILE DIRECTLY.
// It has been generated with ./util/design/gen-otp-mmap.py

`define PART_MUBI_COV(__part_name, __index)                                           \
  bind otp_ctrl cip_mubi_cov_if #(.Width(8)) ``__part_name``_read_lock_mubi_cov_if (  \
    .rst_ni (rst_ni),                                                                 \
    .mubi   (part_access[``__index``].read_lock)                                      \
  );                                                                                  \
  bind otp_ctrl cip_mubi_cov_if #(.Width(8)) ``__part_name``_write_lock_mubi_cov_if ( \
    .rst_ni (rst_ni),                                                                 \
    .mubi   (part_access[``__index``].write_lock)                                     \
  );

`define DAI_MUBI_COV(__part_name, __index)                                                \
  bind otp_ctrl cip_mubi_cov_if #(.Width(8)) dai_``__part_name``_read_lock_mubi_cov_if (  \
    .rst_ni (rst_ni),                                                                     \
    .mubi   (part_access_dai[``__index``].read_lock)                                      \
  );                                                                                      \
  bind otp_ctrl cip_mubi_cov_if #(.Width(8)) dai_``__part_name``_write_lock_mubi_cov_if ( \
    .rst_ni (rst_ni),                                                                     \
    .mubi   (part_access_dai[``__index``].write_lock)                                     \
  );

module otp_ctrl_cov_bind;
  import otp_ctrl_part_pkg::*;

  bind otp_ctrl otp_ctrl_cov_if u_otp_ctrl_cov_if (
    .pwr_otp_o        (pwr_otp_o),
    .lc_otp_program_i (lc_otp_program_i),
    .lc_escalate_en_i (lc_escalate_en_i),
    .flash_otp_key_i  (flash_otp_key_i),
    .sram_otp_key_i   (sram_otp_key_i),
    .otbn_otp_key_i   (otbn_otp_key_i)
  );

  bind otp_ctrl cip_lc_tx_cov_if u_lc_creator_seed_sw_rw_en_cov_if (
    .rst_ni (rst_ni),
    .val    (lc_creator_seed_sw_rw_en_i)
  );

  bind otp_ctrl cip_lc_tx_cov_if u_lc_seed_hw_rd_en_cov_if (
    .rst_ni (rst_ni),
    .val    (lc_seed_hw_rd_en_i)
  );

  bind otp_ctrl cip_lc_tx_cov_if u_lc_dft_en_cov_if (
    .rst_ni (rst_ni),
    .val    (lc_dft_en_i)
  );

  bind otp_ctrl cip_lc_tx_cov_if u_lc_escalate_en_cov_if (
    .rst_ni (rst_ni),
    .val    (lc_escalate_en_i)
  );

  bind otp_ctrl cip_lc_tx_cov_if u_lc_check_byp_en_cov_if (
    .rst_ni (rst_ni),
    .val    (lc_check_byp_en_i)
  );

  // Mubi internal coverage for buffered and unbuffered partitions.
  `PART_MUBI_COV(secret_manuf_partition, otp_ctrl_part_pkg::SecretManufPartitionIdx)
  `PART_MUBI_COV(secret_prod_partition_0, otp_ctrl_part_pkg::SecretProdPartition0Idx)
  `PART_MUBI_COV(secret_prod_partition_1, otp_ctrl_part_pkg::SecretProdPartition1Idx)
  `PART_MUBI_COV(secret_prod_partition_2, otp_ctrl_part_pkg::SecretProdPartition2Idx)
  `PART_MUBI_COV(secret_prod_partition_3, otp_ctrl_part_pkg::SecretProdPartition3Idx)
  `PART_MUBI_COV(sw_manuf_partition, otp_ctrl_part_pkg::SwManufPartitionIdx)
  `PART_MUBI_COV(sw_prod_partition, otp_ctrl_part_pkg::SwProdPartitionIdx)
  `PART_MUBI_COV(secret_lc_unlock_partition, otp_ctrl_part_pkg::SecretLcUnlockPartitionIdx)
  `PART_MUBI_COV(secret_lc_manuf_partition, otp_ctrl_part_pkg::SecretLcManufPartitionIdx)
  `PART_MUBI_COV(secret_lc_prod_partition, otp_ctrl_part_pkg::SecretLcProdPartitionIdx)
  `PART_MUBI_COV(secret_lc_rma_partition, otp_ctrl_part_pkg::SecretLcRmaPartitionIdx)
  `PART_MUBI_COV(svn_partition, otp_ctrl_part_pkg::SvnPartitionIdx)
  `PART_MUBI_COV(vendor_test_partition, otp_ctrl_part_pkg::VendorTestPartitionIdx)

  // Mubi internal coverage for DAI interface access
  `DAI_MUBI_COV(secret_manuf_partition, otp_ctrl_part_pkg::SecretManufPartitionIdx)
  `DAI_MUBI_COV(secret_prod_partition_0, otp_ctrl_part_pkg::SecretProdPartition0Idx)
  `DAI_MUBI_COV(secret_prod_partition_1, otp_ctrl_part_pkg::SecretProdPartition1Idx)
  `DAI_MUBI_COV(secret_prod_partition_2, otp_ctrl_part_pkg::SecretProdPartition2Idx)
  `DAI_MUBI_COV(secret_prod_partition_3, otp_ctrl_part_pkg::SecretProdPartition3Idx)
  `DAI_MUBI_COV(sw_manuf_partition, otp_ctrl_part_pkg::SwManufPartitionIdx)
  `DAI_MUBI_COV(sw_prod_partition, otp_ctrl_part_pkg::SwProdPartitionIdx)
  `DAI_MUBI_COV(secret_lc_unlock_partition, otp_ctrl_part_pkg::SecretLcUnlockPartitionIdx)
  `DAI_MUBI_COV(secret_lc_manuf_partition, otp_ctrl_part_pkg::SecretLcManufPartitionIdx)
  `DAI_MUBI_COV(secret_lc_prod_partition, otp_ctrl_part_pkg::SecretLcProdPartitionIdx)
  `DAI_MUBI_COV(secret_lc_rma_partition, otp_ctrl_part_pkg::SecretLcRmaPartitionIdx)
  `DAI_MUBI_COV(svn_partition, otp_ctrl_part_pkg::SvnPartitionIdx)
  `DAI_MUBI_COV(vendor_test_partition, otp_ctrl_part_pkg::VendorTestPartitionIdx)

`undef PART_MUBI_COV
`undef DAI_MUBI_COV
endmodule
