name: Daily Branch Creation

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Caliptra Subsystem Auto Branching"
          git config --global user.email "nileshbpat@gmail.com"

      - name: Create new branch
        env:
          BRANCH_NAME: msft-daily-$(date +%Y-%m-%d-%H-%M)
        run: |
          # Fetch latest main
          git fetch origin main
          git checkout main
          git pull origin main

          # Create new branch
          git checkout -b $BRANCH_NAME

          # Push new branch to repository
          git push origin $BRANCH_NAME
