# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# This is the top-level workflow to run on all pull-requests, and invokes
# several other workflow dependencies
name: Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  # Call auxiliary workflows
  pre_run:
    uses: ./.github/workflows/pre-run-check.yml
  doc_gen:
    uses: ./.github/workflows/doc-gen.yml
    if: ${{ (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'push') }}
    permissions:
      pages: write
      id-token: write
  post_run:
    name: Call Post Run Final
    runs-on: ubuntu-22.04
    needs: [pre_run]
    steps:
      - name: Checkout RTL repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            submodules: recursive
      - run: echo "Finalize"
    
